// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package opnsense

import (
	"github.com/biptec/opnsense-go/pkg/api"
	"github.com/biptec/opnsense-go/pkg/auth"
	"github.com/biptec/opnsense-go/pkg/bind"
	"github.com/biptec/opnsense-go/pkg/core"
	"github.com/biptec/opnsense-go/pkg/cron"
	"github.com/biptec/opnsense-go/pkg/diagnostics"
	"github.com/biptec/opnsense-go/pkg/dnsmasq"
	"github.com/biptec/opnsense-go/pkg/dyndns"
	"github.com/biptec/opnsense-go/pkg/firewall"
	"github.com/biptec/opnsense-go/pkg/interfaces"
	"github.com/biptec/opnsense-go/pkg/ipsec"
	"github.com/biptec/opnsense-go/pkg/kea"
	"github.com/biptec/opnsense-go/pkg/openvpn"
	"github.com/biptec/opnsense-go/pkg/quagga"
	"github.com/biptec/opnsense-go/pkg/routes"
	"github.com/biptec/opnsense-go/pkg/routing"
	"github.com/biptec/opnsense-go/pkg/trust"
	"github.com/biptec/opnsense-go/pkg/unbound"
	"github.com/biptec/opnsense-go/pkg/wireguard"
)

// Client defines a client interface for the Proxmox Virtual Environment API.
type Client interface {
	Auth() *auth.Controller
	Bind() *bind.Controller
	Core() *core.Controller
	Cron() *cron.Controller
	Diagnostics() *diagnostics.Controller
	Dnsmasq() *dnsmasq.Controller
	Dyndns() *dyndns.Controller
	Firewall() *firewall.Controller
	Interfaces() *interfaces.Controller
	Ipsec() *ipsec.Controller
	Kea() *kea.Controller
	Openvpn() *openvpn.Controller
	Quagga() *quagga.Controller
	Routes() *routes.Controller
	Routing() *routing.Controller
	Trust() *trust.Controller
	Unbound() *unbound.Controller
	Wireguard() *wireguard.Controller
}

type client struct {
	a *api.Client
}

// NewClient creates a new API client.
func NewClient(a *api.Client) Client {
	return &client{a: a}
}

func (c *client) Auth() *auth.Controller {
	return &auth.Controller{Api: c.a}
}

func (c *client) Bind() *bind.Controller {
	return &bind.Controller{Api: c.a}
}

func (c *client) Core() *core.Controller {
	return &core.Controller{Api: c.a}
}

func (c *client) Cron() *cron.Controller {
	return &cron.Controller{Api: c.a}
}

func (c *client) Diagnostics() *diagnostics.Controller {
	return &diagnostics.Controller{Api: c.a}
}

func (c *client) Dnsmasq() *dnsmasq.Controller {
	return &dnsmasq.Controller{Api: c.a}
}

func (c *client) Dyndns() *dyndns.Controller {
	return &dyndns.Controller{Api: c.a}
}

func (c *client) Firewall() *firewall.Controller {
	return &firewall.Controller{Api: c.a}
}

func (c *client) Interfaces() *interfaces.Controller {
	return &interfaces.Controller{Api: c.a}
}

func (c *client) Ipsec() *ipsec.Controller {
	return &ipsec.Controller{Api: c.a}
}

func (c *client) Kea() *kea.Controller {
	return &kea.Controller{Api: c.a}
}

func (c *client) Openvpn() *openvpn.Controller {
	return &openvpn.Controller{Api: c.a}
}

func (c *client) Quagga() *quagga.Controller {
	return &quagga.Controller{Api: c.a}
}

func (c *client) Routes() *routes.Controller {
	return &routes.Controller{Api: c.a}
}

func (c *client) Routing() *routing.Controller {
	return &routing.Controller{Api: c.a}
}

func (c *client) Trust() *trust.Controller {
	return &trust.Controller{Api: c.a}
}

func (c *client) Unbound() *unbound.Controller {
	return &unbound.Controller{Api: c.a}
}

func (c *client) Wireguard() *wireguard.Controller {
	return &wireguard.Controller{Api: c.a}
}
