// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package api_extensions

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type CarpHealthActionResult struct {
	Status      string                 `json:"status,omitempty"`
	Result      string                 `json:"result,omitempty"`
	Validations map[string]interface{} `json:"validations,omitempty"`
}

type CarpHealthCheckStatus struct {
	UUID                  string                  `json:"uuid"`
	Name                  string                  `json:"name"`
	Interface             string                  `json:"interface"`
	Device                string                  `json:"device"`
	Target                string                  `json:"target"`
	Scope                 string                  `json:"scope"`
	VHID                  int                     `json:"vhid"`
	VHIDTargets           []string                `json:"vhid_targets"`
	ConfiguredVHIDTargets []string                `json:"configured_vhid_targets"`
	FailureAdvSkew        int                     `json:"failure_advskew"`
	VHIDStates            []CarpHealthVHIDStatus  `json:"vhid_states"`
	FallbackRoutes        []CarpHealthRouteStatus `json:"fallback_routes"`
	CarpState             string                  `json:"carp_state"`
	ConfiguredAdvSkew     *int                    `json:"configured_advskew"`
	CurrentAdvSkew        *int                    `json:"current_advskew"`
	ControlOK             bool                    `json:"control_ok"`
	Healthy               bool                    `json:"healthy"`
	Failures              int                     `json:"failures"`
	Successes             int                     `json:"successes"`
}

type CarpHealthGlobalStatus struct {
	Active     bool `json:"active"`
	CheckCount int  `json:"check_count"`
	Ready      bool `json:"ready"`
	Healthy    bool `json:"healthy"`
}

type CarpHealthResponse struct {
	CarpHealth CarpHealthSettings `json:"carp_health"`
}

type CarpHealthRouteStatus struct {
	Key              string `json:"key"`
	CheckUUID        string `json:"check_uuid"`
	Check            string `json:"check"`
	Family           string `json:"family"`
	Destination      string `json:"destination"`
	Gateway          string `json:"gateway"`
	DesiredInstalled bool   `json:"desired_installed"`
	Installed        bool   `json:"installed"`
	Managed          bool   `json:"managed"`
	ControlOK        bool   `json:"control_ok"`
	Retired          bool   `json:"retired"`
	Error            string `json:"error"`
}

type CarpHealthSettings struct {
	Enabled           api.BoolString `json:"enabled"`
	Interval          string         `json:"interval"`
	FailureThreshold  string         `json:"failure_threshold"`
	RecoveryThreshold string         `json:"recovery_threshold"`
}

type CarpHealthStatusResponse struct {
	Status          string                  `json:"status"`
	Enabled         bool                    `json:"enabled"`
	Ready           bool                    `json:"ready"`
	Healthy         bool                    `json:"healthy"`
	ProbeHealthy    bool                    `json:"probe_healthy"`
	ControlOK       bool                    `json:"control_ok"`
	Running         bool                    `json:"running"`
	Timestamp       float64                 `json:"timestamp"`
	ConfigSignature string                  `json:"config_signature"`
	Global          CarpHealthGlobalStatus  `json:"global"`
	VHIDs           []CarpHealthVHIDStatus  `json:"vhids"`
	Routes          []CarpHealthRouteStatus `json:"routes"`
	Checks          []CarpHealthCheckStatus `json:"checks"`
}

type CarpHealthVHIDStatus struct {
	Key               string   `json:"key"`
	Interface         string   `json:"interface"`
	Device            string   `json:"device"`
	VHID              int      `json:"vhid"`
	Checks            []string `json:"checks"`
	Ready             bool     `json:"ready"`
	Healthy           bool     `json:"healthy"`
	DesiredDemoted    bool     `json:"desired_demoted"`
	DesiredAdvSkew    *int     `json:"desired_advskew"`
	ConfiguredAdvSkew *int     `json:"configured_advskew"`
	CurrentAdvSkew    *int     `json:"current_advskew"`
	CarpState         string   `json:"carp_state"`
	ControlOK         bool     `json:"control_ok"`
	Retired           bool     `json:"retired"`
	Error             string   `json:"error"`
}

// CarpHealthGet executes the Get RPC call of the CarpHealth controller
func (c *Controller) CarpHealthGet(ctx context.Context) (*CarpHealthResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/api_extensions/carp_health/get", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &CarpHealthResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("get call failed: %w", err)
	}
	return result, nil
}

// CarpHealthSet executes the Set RPC call of the CarpHealth controller
func (c *Controller) CarpHealthSet(ctx context.Context, settings *CarpHealthSettings) (*CarpHealthActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["carp_health"] = settings

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/api_extensions/carp_health/set", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &CarpHealthActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("set call failed: %w", err)
	}
	return result, nil
}

// CarpHealthReconfigure executes the Reconfigure RPC call of the CarpHealth controller
func (c *Controller) CarpHealthReconfigure(ctx context.Context) (*CarpHealthActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/api_extensions/carp_health/reconfigure", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &CarpHealthActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("reconfigure call failed: %w", err)
	}
	return result, nil
}

// CarpHealthStatus executes the Status RPC call of the CarpHealth controller
func (c *Controller) CarpHealthStatus(ctx context.Context) (*CarpHealthStatusResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/api_extensions/carp_health/status", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &CarpHealthStatusResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("status call failed: %w", err)
	}
	return result, nil
}
