// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package api_extensions

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type CarpHealthActionResult struct {
	Status      string                 `json:"status,omitempty"`
	Result      string                 `json:"result,omitempty"`
	Validations map[string]interface{} `json:"validations,omitempty"`
}

type CarpHealthCheckStatus struct {
	UUID      string `json:"uuid"`
	Name      string `json:"name"`
	Interface string `json:"interface"`
	Device    string `json:"device"`
	Target    string `json:"target"`
	Healthy   bool   `json:"healthy"`
	Failures  int    `json:"failures"`
	Successes int    `json:"successes"`
}

type CarpHealthResponse struct {
	CarpHealth CarpHealthSettings `json:"carp_health"`
}

type CarpHealthSettings struct {
	Enabled           api.BoolString `json:"enabled"`
	Interval          string         `json:"interval"`
	FailureThreshold  string         `json:"failure_threshold"`
	RecoveryThreshold string         `json:"recovery_threshold"`
}

type CarpHealthStatusResponse struct {
	Status          string                  `json:"status"`
	Enabled         bool                    `json:"enabled"`
	Ready           bool                    `json:"ready"`
	Healthy         bool                    `json:"healthy"`
	Running         bool                    `json:"running"`
	Timestamp       float64                 `json:"timestamp"`
	ConfigSignature string                  `json:"config_signature"`
	Checks          []CarpHealthCheckStatus `json:"checks"`
}

// CarpHealthGet executes the Get RPC call of the CarpHealth controller
func (c *Controller) CarpHealthGet(ctx context.Context) (*CarpHealthResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/api_extensions/carp_health/get", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &CarpHealthResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("get call failed: %w", err)
	}
	return result, nil
}

// CarpHealthSet executes the Set RPC call of the CarpHealth controller
func (c *Controller) CarpHealthSet(ctx context.Context, settings *CarpHealthSettings) (*CarpHealthActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["carp_health"] = settings

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/api_extensions/carp_health/set", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &CarpHealthActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("set call failed: %w", err)
	}
	return result, nil
}

// CarpHealthReconfigure executes the Reconfigure RPC call of the CarpHealth controller
func (c *Controller) CarpHealthReconfigure(ctx context.Context) (*CarpHealthActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/api_extensions/carp_health/reconfigure", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &CarpHealthActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("reconfigure call failed: %w", err)
	}
	return result, nil
}

// CarpHealthStatus executes the Status RPC call of the CarpHealth controller
func (c *Controller) CarpHealthStatus(ctx context.Context) (*CarpHealthStatusResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/api_extensions/carp_health/status", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &CarpHealthStatusResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("status call failed: %w", err)
	}
	return result, nil
}
