// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package api_extensions

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var CarpHealthCheckOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/api_extensions/carp_health/addCheck", Method: "POST"},
	Read:        api.Endpoint{Path: "/api_extensions/carp_health/getCheck", Method: "GET"},
	Update:      api.Endpoint{Path: "/api_extensions/carp_health/setCheck", Method: "POST"},
	Delete:      api.Endpoint{Path: "/api_extensions/carp_health/delCheck", Method: "POST"},
	Search:      api.Endpoint{Path: "/api_extensions/carp_health/searchCheck", Method: "GET"},
	Reconfigure: api.Endpoint{Path: "/api_extensions/carp_health/reconfigure", Method: "POST"},
	Monad:       "check",
}

// Data structs

type CarpHealthCheck struct {
	Enabled                    api.BoolString      `json:"enabled"`
	Name                       string              `json:"name"`
	Interface                  api.SelectedMap     `json:"interface"`
	Target                     string              `json:"target"`
	Scope                      api.SelectedMap     `json:"scope"`
	VHID                       string              `json:"vhid"`
	FailureAdvSkew             string              `json:"failure_advskew"`
	VHIDTargets                api.SelectedMapList `json:"vhid_targets"`
	FallbackIPv4Target         string              `json:"fallback_ipv4_target"`
	FallbackIPv4Gateway        string              `json:"fallback_ipv4_gateway"`
	FallbackIPv6Target         string              `json:"fallback_ipv6_target"`
	FallbackIPv6Gateway        string              `json:"fallback_ipv6_gateway"`
	FallbackIPv4DefaultGateway string              `json:"fallback_ipv4_default_gateway"`
	FallbackIPv6DefaultGateway string              `json:"fallback_ipv6_default_gateway"`
	BackupIPv4DefaultGateway   string              `json:"backup_ipv4_default_gateway"`
	BackupIPv6DefaultGateway   string              `json:"backup_ipv6_default_gateway"`
}

// CRUD operations

func (c *Controller) AddCarpHealthCheck(ctx context.Context, resource *CarpHealthCheck) (string, error) {
	return api.Add(c.Client(), ctx, CarpHealthCheckOpts, resource)
}

func (c *Controller) GetCarpHealthCheck(ctx context.Context, id string) (*CarpHealthCheck, error) {
	return api.Get(c.Client(), ctx, CarpHealthCheckOpts, &CarpHealthCheck{}, id)
}

func (c *Controller) SearchCarpHealthCheck(ctx context.Context) (*api.SearchResponse[CarpHealthCheck], error) {
	return api.Search[CarpHealthCheck](c.Client(), ctx, CarpHealthCheckOpts.Search)
}

func (c *Controller) UpdateCarpHealthCheck(ctx context.Context, id string, resource *CarpHealthCheck) error {
	return api.Update(c.Client(), ctx, CarpHealthCheckOpts, resource, id)
}

func (c *Controller) DeleteCarpHealthCheck(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, CarpHealthCheckOpts, id)
}
