// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package api_extensions

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type DnsActionResult struct {
	Status      string            `json:"status"`
	Validations map[string]string `json:"validations,omitempty"`
	Result      string            `json:"result,omitempty"`
}

type DnsResponse struct {
	DNS DnsSettings `json:"dns"`
}

type DnsSettings struct {
	Servers         []string `json:"servers"`
	AllowOverride   bool     `json:"allow_override"`
	UseLocalService bool     `json:"use_local_service"`
}

// DnsGet executes the Get RPC call of the Dns controller
func (c *Controller) DnsGet(ctx context.Context) (*DnsResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/api_extensions/dns/get", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &DnsResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("get call failed: %w", err)
	}
	return result, nil
}

// DnsSet executes the Set RPC call of the Dns controller
func (c *Controller) DnsSet(ctx context.Context, settings *DnsSettings) (*DnsActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["dns"] = settings

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/api_extensions/dns/set", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &DnsActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("set call failed: %w", err)
	}
	return result, nil
}

// DnsReconfigure executes the Reconfigure RPC call of the Dns controller
func (c *Controller) DnsReconfigure(ctx context.Context) (*DnsActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/api_extensions/dns/reconfigure", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &DnsActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("reconfigure call failed: %w", err)
	}
	return result, nil
}
