// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package api_extensions

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var InterfacePolicyAssignmentOpts = api.ReqOpts{
	Create: api.Endpoint{Path: "/api_extensions/interface_policy/addAssignment", Method: "POST"},
	Read:   api.Endpoint{Path: "/api_extensions/interface_policy/getAssignment", Method: "GET"},
	Update: api.Endpoint{Path: "/api_extensions/interface_policy/setAssignment", Method: "POST"},
	Delete: api.Endpoint{Path: "/api_extensions/interface_policy/delAssignment", Method: "POST"},
	Search: api.Endpoint{Path: "/api_extensions/interface_policy/searchAssignment", Method: "GET"},
	Monad:  "assignment",
}

// Data structs

type InterfacePolicyAssignment struct {
	Interface api.SelectedMap `json:"interface"`
	PolicyID  api.SelectedMap `json:"policy_id"`
}

// CRUD operations

func (c *Controller) AddInterfacePolicyAssignment(ctx context.Context, resource *InterfacePolicyAssignment) (string, error) {
	return api.Add(c.Client(), ctx, InterfacePolicyAssignmentOpts, resource)
}

func (c *Controller) GetInterfacePolicyAssignment(ctx context.Context, id string) (*InterfacePolicyAssignment, error) {
	return api.Get(c.Client(), ctx, InterfacePolicyAssignmentOpts, &InterfacePolicyAssignment{}, id)
}

func (c *Controller) SearchInterfacePolicyAssignment(ctx context.Context) (*api.SearchResponse[InterfacePolicyAssignment], error) {
	return api.Search[InterfacePolicyAssignment](c.Client(), ctx, InterfacePolicyAssignmentOpts.Search)
}

func (c *Controller) UpdateInterfacePolicyAssignment(ctx context.Context, id string, resource *InterfacePolicyAssignment) error {
	return api.Update(c.Client(), ctx, InterfacePolicyAssignmentOpts, resource, id)
}

func (c *Controller) DeleteInterfacePolicyAssignment(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, InterfacePolicyAssignmentOpts, id)
}
