// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package api_extensions

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var InterfaceSyncPolicyOpts = api.ReqOpts{
	Create: api.Endpoint{Path: "/api_extensions/interface_policy/addPolicy", Method: "POST"},
	Read:   api.Endpoint{Path: "/api_extensions/interface_policy/getPolicy", Method: "GET"},
	Update: api.Endpoint{Path: "/api_extensions/interface_policy/setPolicy", Method: "POST"},
	Delete: api.Endpoint{Path: "/api_extensions/interface_policy/delPolicy", Method: "POST"},
	Search: api.Endpoint{Path: "/api_extensions/interface_policy/searchPolicy", Method: "GET"},
	Monad:  "policy",
}

// Data structs

type InterfaceSyncPolicy struct {
	ID          string         `json:"id"`
	Description string         `json:"description"`
	Synchronize api.BoolString `json:"synchronize"`
}

// CRUD operations

func (c *Controller) AddInterfaceSyncPolicy(ctx context.Context, resource *InterfaceSyncPolicy) (string, error) {
	return api.Add(c.Client(), ctx, InterfaceSyncPolicyOpts, resource)
}

func (c *Controller) GetInterfaceSyncPolicy(ctx context.Context, id string) (*InterfaceSyncPolicy, error) {
	return api.Get(c.Client(), ctx, InterfaceSyncPolicyOpts, &InterfaceSyncPolicy{}, id)
}

func (c *Controller) SearchInterfaceSyncPolicy(ctx context.Context) (*api.SearchResponse[InterfaceSyncPolicy], error) {
	return api.Search[InterfaceSyncPolicy](c.Client(), ctx, InterfaceSyncPolicyOpts.Search)
}

func (c *Controller) UpdateInterfaceSyncPolicy(ctx context.Context, id string, resource *InterfaceSyncPolicy) error {
	return api.Update(c.Client(), ctx, InterfaceSyncPolicyOpts, resource, id)
}

func (c *Controller) DeleteInterfaceSyncPolicy(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, InterfaceSyncPolicyOpts, id)
}
