// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package api_extensions

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type NtpActionResult struct {
	Status      string            `json:"status"`
	Validations map[string]string `json:"validations,omitempty"`
}

type NtpResponse struct {
	NTP NtpSettings `json:"ntp"`
}

type NtpServer struct {
	Host     string `json:"host"`
	NoSelect bool   `json:"noselect"`
	Prefer   bool   `json:"prefer"`
	IBurst   bool   `json:"iburst"`
	Pool     bool   `json:"pool"`
}

type NtpSettings struct {
	Enabled              bool        `json:"enabled"`
	Servers              []NtpServer `json:"servers"`
	Interfaces           []string    `json:"interfaces"`
	Orphan               int         `json:"orphan"`
	MaxClock             int         `json:"max_clock"`
	ClientMode           bool        `json:"client_mode"`
	KissOfDeath          bool        `json:"kiss_of_death"`
	RateLimiting         bool        `json:"rate_limiting"`
	DenyModifications    bool        `json:"deny_modifications"`
	DisableQueries       bool        `json:"disable_queries"`
	DisableServing       bool        `json:"disable_serving"`
	DenyPeerAssociations bool        `json:"deny_peer_associations"`
	DenyTrapService      bool        `json:"deny_trap_service"`
}

// NtpGet executes the Get RPC call of the Ntp controller
func (c *Controller) NtpGet(ctx context.Context) (*NtpResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/api_extensions/ntp/get", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &NtpResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("get call failed: %w", err)
	}
	return result, nil
}

// NtpSet executes the Set RPC call of the Ntp controller
func (c *Controller) NtpSet(ctx context.Context, settings *NtpSettings) (*NtpActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["ntp"] = settings

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/api_extensions/ntp/set", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &NtpActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("set call failed: %w", err)
	}
	return result, nil
}

// NtpReconfigure executes the Reconfigure RPC call of the Ntp controller
func (c *Controller) NtpReconfigure(ctx context.Context) (*NtpActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/api_extensions/ntp/reconfigure", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &NtpActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("reconfigure call failed: %w", err)
	}
	return result, nil
}
