// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package api_extensions

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type PackageResponse struct {
	Status  string       `json:"status"`
	Message string       `json:"message,omitempty"`
	Package PackageState `json:"package"`
}

type PackageState struct {
	Name       string `json:"name"`
	Installed  bool   `json:"installed"`
	Provided   bool   `json:"provided"`
	Version    string `json:"version"`
	Locked     bool   `json:"locked"`
	Repository string `json:"repository"`
	Origin     string `json:"origin"`
}

// PackageGet executes the Get RPC call of the Package controller
func (c *Controller) PackageGet(ctx context.Context, packageName string) (*PackageResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, packageName)

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/api_extensions/package/get", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &PackageResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("get call failed: %w", err)
	}
	return result, nil
}
