// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package api_extensions

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type SshActionResult struct {
	Status      string            `json:"status"`
	Validations map[string]string `json:"validations,omitempty"`
	Result      string            `json:"result,omitempty"`
}

type SshResponse struct {
	SSH SshSettings `json:"ssh"`
}

type SshSettings struct {
	Enabled                bool     `json:"enabled"`
	Port                   int      `json:"port"`
	Interfaces             []string `json:"interfaces"`
	PasswordAuthentication bool     `json:"password_authentication"`
	PermitRootLogin        bool     `json:"permit_root_login"`
}

// SshGet executes the Get RPC call of the Ssh controller
func (c *Controller) SshGet(ctx context.Context) (*SshResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/api_extensions/ssh/get", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &SshResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("get call failed: %w", err)
	}
	return result, nil
}

// SshSet executes the Set RPC call of the Ssh controller
func (c *Controller) SshSet(ctx context.Context, settings *SshSettings) (*SshActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["ssh"] = settings

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/api_extensions/ssh/set", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &SshActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("set call failed: %w", err)
	}
	return result, nil
}

// SshReconfigure executes the Reconfigure RPC call of the Ssh controller
func (c *Controller) SshReconfigure(ctx context.Context) (*SshActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/api_extensions/ssh/reconfigure", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &SshActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("reconfigure call failed: %w", err)
	}
	return result, nil
}
