// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package api_extensions

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type WebguiActionResult struct {
	Status      string            `json:"status"`
	Validations map[string]string `json:"validations,omitempty"`
	MessageUUID string            `json:"msg_uuid,omitempty"`
	Result      string            `json:"result,omitempty"`
}

type WebguiResponse struct {
	Webgui WebguiSettings `json:"webgui"`
}

type WebguiSettings struct {
	Protocol            string   `json:"protocol"`
	Port                int      `json:"port"`
	Interfaces          []string `json:"interfaces"`
	CertificateRef      string   `json:"certificate_ref"`
	SessionTimeout      *int     `json:"session_timeout"`
	HSTS                bool     `json:"hsts"`
	DisableHTTPRedirect bool     `json:"disable_http_redirect"`
	AlternateHostnames  []string `json:"alternate_hostnames"`
}

// WebguiGet executes the Get RPC call of the Webgui controller
func (c *Controller) WebguiGet(ctx context.Context) (*WebguiResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/api_extensions/webgui/get", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &WebguiResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("get call failed: %w", err)
	}
	return result, nil
}

// WebguiSet executes the Set RPC call of the Webgui controller
func (c *Controller) WebguiSet(ctx context.Context, settings *WebguiSettings) (*WebguiActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["webgui"] = settings

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/api_extensions/webgui/set", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &WebguiActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("set call failed: %w", err)
	}
	return result, nil
}

// WebguiReconfigure executes the Reconfigure RPC call of the Webgui controller
func (c *Controller) WebguiReconfigure(ctx context.Context) (*WebguiActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/api_extensions/webgui/reconfigure", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &WebguiActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("reconfigure call failed: %w", err)
	}
	return result, nil
}
