// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package ipsec

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var IPsecPSKOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/ipsec/pre_shared_keys/add_item", Method: "POST"},
	Read:        api.Endpoint{Path: "/ipsec/pre_shared_keys/get_item", Method: "GET"},
	Update:      api.Endpoint{Path: "/ipsec/pre_shared_keys/set_item", Method: "POST"},
	Delete:      api.Endpoint{Path: "/ipsec/pre_shared_keys/del_item", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/ipsec/service/reconfigure", Method: "POST"},
	Monad:       "preSharedKey",
}

// Data structs

type IPsecPSK struct {
	IdentityLocal  string          `json:"ident"`
	IdentityRemote string          `json:"remote_ident"`
	PreSharedKey   string          `json:"Key"`
	Type           api.SelectedMap `json:"keyType"`
	Description    string          `json:"description"`
}

// CRUD operations

func (c *Controller) AddIPsecPSK(ctx context.Context, resource *IPsecPSK) (string, error) {
	return api.Add(c.Client(), ctx, IPsecPSKOpts, resource)
}

func (c *Controller) GetIPsecPSK(ctx context.Context, id string) (*IPsecPSK, error) {
	return api.Get(c.Client(), ctx, IPsecPSKOpts, &IPsecPSK{}, id)
}

func (c *Controller) UpdateIPsecPSK(ctx context.Context, id string, resource *IPsecPSK) error {
	return api.Update(c.Client(), ctx, IPsecPSKOpts, resource, id)
}

func (c *Controller) DeleteIPsecPSK(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, IPsecPSKOpts, id)
}
