// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package openvpn

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var StaticKeyOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/openvpn/instances/add_static_key", Method: "POST"},
	Read:        api.Endpoint{Path: "/openvpn/instances/get_static_key", Method: "GET"},
	Update:      api.Endpoint{Path: "/openvpn/instances/set_static_key", Method: "POST"},
	Delete:      api.Endpoint{Path: "/openvpn/instances/del_static_key", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/openvpn/service/reconfigure", Method: "POST"},
	Monad:       "statickey",
}

// Data structs

type StaticKey struct {
	Mode        api.SelectedMap `json:"mode"`
	Key         string          `json:"key"`
	Description string          `json:"description"`
}

// CRUD operations

func (c *Controller) AddStaticKey(ctx context.Context, resource *StaticKey) (string, error) {
	return api.Add(c.Client(), ctx, StaticKeyOpts, resource)
}

func (c *Controller) GetStaticKey(ctx context.Context, id string) (*StaticKey, error) {
	return api.Get(c.Client(), ctx, StaticKeyOpts, &StaticKey{}, id)
}

func (c *Controller) UpdateStaticKey(ctx context.Context, id string, resource *StaticKey) error {
	return api.Update(c.Client(), ctx, StaticKeyOpts, resource, id)
}

func (c *Controller) DeleteStaticKey(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, StaticKeyOpts, id)
}
