// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package firewall

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var AliasOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/firewall/alias/addItem", Method: "POST"},
	Read:        api.Endpoint{Path: "/firewall/alias/getItem", Method: "GET"},
	Update:      api.Endpoint{Path: "/firewall/alias/setItem", Method: "POST"},
	Delete:      api.Endpoint{Path: "/firewall/alias/delItem", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/firewall/alias/reconfigure", Method: "POST"},
	Monad:       "alias",
}

// Data structs

type Alias struct {
	Enabled        string                `json:"enabled"`
	Name           string                `json:"name"`
	Type           api.SelectedMap       `json:"type"`
	IPProtocol     api.SelectedMapList   `json:"proto"`
	Interface      api.SelectedMap       `json:"interface"`
	Content        api.SelectedMapListNL `json:"content"`
	Categories     api.SelectedMapList   `json:"categories"`
	UpdateFreq     string                `json:"updatefreq"`
	PathExpression string                `json:"path_expression"`
	Statistics     string                `json:"counters"`
	Description    string                `json:"description"`
}

// CRUD operations

func (c *Controller) AddAlias(ctx context.Context, resource *Alias) (string, error) {
	return api.Add(c.Client(), ctx, AliasOpts, resource)
}

func (c *Controller) GetAlias(ctx context.Context, id string) (*Alias, error) {
	return api.Get(c.Client(), ctx, AliasOpts, &Alias{}, id)
}

func (c *Controller) UpdateAlias(ctx context.Context, id string, resource *Alias) error {
	return api.Update(c.Client(), ctx, AliasOpts, resource, id)
}

func (c *Controller) DeleteAlias(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, AliasOpts, id)
}
