// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package firewall

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var GroupOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/firewall/group/addItem", Method: "POST"},
	Read:        api.Endpoint{Path: "/firewall/group/getItem", Method: "GET"},
	Update:      api.Endpoint{Path: "/firewall/group/setItem", Method: "POST"},
	Delete:      api.Endpoint{Path: "/firewall/group/delItem", Method: "POST"},
	Search:      api.Endpoint{Path: "/firewall/group/searchItem", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/firewall/group/reconfigure", Method: "POST"},
	Monad:       "group",
}

// Data structs

type Group struct {
	UUID        string              `json:"uuid,omitempty"`
	Name        string              `json:"ifname"`
	Members     api.SelectedMapList `json:"members"`
	NoGroup     string              `json:"nogroup"`
	Sequence    string              `json:"sequence"`
	Description string              `json:"descr"`
}

// CRUD operations

func (c *Controller) AddGroup(ctx context.Context, resource *Group) (string, error) {
	return api.Add(c.Client(), ctx, GroupOpts, resource)
}

func (c *Controller) GetGroup(ctx context.Context, id string) (*Group, error) {
	return api.Get(c.Client(), ctx, GroupOpts, &Group{}, id)
}

func (c *Controller) SearchGroup(ctx context.Context) (*api.SearchResponse[Group], error) {
	return api.Search[Group](c.Client(), ctx, GroupOpts.Search)
}

func (c *Controller) UpdateGroup(ctx context.Context, id string, resource *Group) error {
	return api.Update(c.Client(), ctx, GroupOpts, resource, id)
}

func (c *Controller) DeleteGroup(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, GroupOpts, id)
}
