// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package firewall

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var NptOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/firewall/npt/addRule", Method: "POST"},
	Read:        api.Endpoint{Path: "/firewall/npt/getRule", Method: "GET"},
	Update:      api.Endpoint{Path: "/firewall/npt/setRule", Method: "POST"},
	Delete:      api.Endpoint{Path: "/firewall/npt/delRule", Method: "POST"},
	Search:      api.Endpoint{Path: "/firewall/npt/searchRule", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/firewall/npt/apply", Method: "POST"},
	Monad:       "rule",
}

// Data structs

type Npt struct {
	UUID           string              `json:"uuid,omitempty"`
	Enabled        string              `json:"enabled"`
	Log            string              `json:"log"`
	Sequence       string              `json:"sequence"`
	Categories     api.SelectedMapList `json:"categories"`
	Description    string              `json:"description"`
	Interface      api.SelectedMap     `json:"interface"`
	SourceNet      string              `json:"source_net"`
	DestinationNet string              `json:"destination_net"`
	TrackInterface api.SelectedMap     `json:"trackif"`
}

// CRUD operations

func (c *Controller) AddNpt(ctx context.Context, resource *Npt) (string, error) {
	return api.Add(c.Client(), ctx, NptOpts, resource)
}

func (c *Controller) GetNpt(ctx context.Context, id string) (*Npt, error) {
	return api.Get(c.Client(), ctx, NptOpts, &Npt{}, id)
}

func (c *Controller) SearchNpt(ctx context.Context) (*api.SearchResponse[Npt], error) {
	return api.Search[Npt](c.Client(), ctx, NptOpts.Search)
}

func (c *Controller) UpdateNpt(ctx context.Context, id string, resource *Npt) error {
	return api.Update(c.Client(), ctx, NptOpts, resource, id)
}

func (c *Controller) DeleteNpt(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, NptOpts, id)
}
