// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package firewall

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type SourceNATApplyResult struct {
	Status string `json:"status"`
}

type SourceNATGeneralSettings struct {
	Mode api.SelectedMap `json:"snat_mode"`
}

type SourceNATSettings struct {
	General SourceNATGeneralSettings `json:"general"`
}

type SourceNATSettingsResponse struct {
	Filter SourceNATSettings `json:"filter"`
}

// SourceNATSettingsGet executes the Get RPC call of the SourceNATSettings controller
func (c *Controller) SourceNATSettingsGet(ctx context.Context) (*SourceNATSettingsResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/firewall/source_nat/get", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &SourceNATSettingsResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("get call failed: %w", err)
	}
	return result, nil
}

// SourceNATSettingsSet executes the Set RPC call of the SourceNATSettings controller
func (c *Controller) SourceNATSettingsSet(ctx context.Context, filter *SourceNATSettings) (*api.ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["filter"] = filter

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/firewall/source_nat/set", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &api.ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("set call failed: %w", err)
	}
	return result, nil
}

// SourceNATSettingsApply executes the Apply RPC call of the SourceNATSettings controller
func (c *Controller) SourceNATSettingsApply(ctx context.Context) (*SourceNATApplyResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/firewall/source_nat/apply", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &SourceNATApplyResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("apply call failed: %w", err)
	}
	return result, nil
}
