// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package interfaces

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type AssignmentSearchResponse struct {
	Total    int                   `json:"total"`
	RowCount int                   `json:"rowCount"`
	Current  int                   `json:"current"`
	Rows     []AssignmentSearchRow `json:"rows"`
}

type AssignmentSearchRow struct {
	Identifier string `json:"identifier,omitempty"`
	UUID       string `json:"uuid,omitempty"`
}

// AssignmentSearch executes the Search RPC call of the Assignment controller
func (c *Controller) AssignmentSearch(ctx context.Context, rowCount string) (*AssignmentSearchResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["rowCount"] = rowCount

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/interfaces/assignment/search_item",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &AssignmentSearchResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("rpc Search failed: %w", err)
	}
	return result, nil
}
