// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var AssignmentOpts = api.ReqOpts{
	AddEndpoint:         "/interfaces/assignment/add_item",
	GetEndpoint:         "/interfaces/assignment/get_item",
	UpdateEndpoint:      "/interfaces/assignment/set_item",
	DeleteEndpoint:      "/interfaces/assignment/del_item",
	ReconfigureEndpoint: "/interfaces/assignment/reconfigure",
	Monad:               "interface",
}

// Data structs

type Assignment struct {
	Description                  string          `json:"descr"`
	Identifier                   string          `json:"identifier,omitempty"`
	Icon                         string          `json:"icon,omitempty"`
	OptionGroup                  string          `json:"optgroup,omitempty"`
	Device                       api.SelectedMap `json:"if"`
	Lock                         string          `json:"lock"`
	Enabled                      string          `json:"enable"`
	BlockPrivateNetworks         string          `json:"blockpriv"`
	BlockBogonNetworks           string          `json:"blockbogons"`
	GatewayInterface             string          `json:"gateway_interface"`
	PromiscuousMode              string          `json:"promisc"`
	SpoofMAC                     string          `json:"spoofmac"`
	MTU                          string          `json:"mtu"`
	MSS                          string          `json:"mss"`
	IPv4Mode                     api.SelectedMap `json:"type"`
	DHCPHostname                 string          `json:"dhcphostname"`
	IPv4AliasAddress             string          `json:"alias-address"`
	IPv4AliasPrefixLength        string          `json:"alias-subnet"`
	DHCPRejectFrom               string          `json:"dhcprejectfrom"`
	IPv6Mode                     api.SelectedMap `json:"type6"`
	DHCPv6PrefixDelegationLength string          `json:"dhcp6-ia-pd-len"`
	DHCPv6SendPrefixHint         string          `json:"dhcp6-ia-pd-send-hint"`
	DHCPv6PrefixOnly             string          `json:"dhcp6prefixonly"`
	DHCPv6UseIPv4Connectivity    string          `json:"dhcp6usev4iface"`
	DHCPv6VLANPriority           string          `json:"dhcp6vlanprio"`
	IPv6TrackInterface           string          `json:"track6-interface"`
	IPv6TrackPrefixID            string          `json:"track6-prefix-id"`
	IPv6TrackPrefixAssociation   string          `json:"track6_assoc_pd"`
	IPv4Address                  string          `json:"ipaddr"`
	IPv4PrefixLength             string          `json:"subnet"`
	IPv4Gateway                  string          `json:"gateway"`
	IPv6Address                  string          `json:"ipaddrv6"`
	IPv6PrefixLength             string          `json:"subnetv6"`
	IPv6Gateway                  string          `json:"gatewayv6"`
}

// CRUD operations

func (c *Controller) GetAssignment(ctx context.Context, id string) (*Assignment, error) {
	return api.Get(c.Client(), ctx, AssignmentOpts, &Assignment{}, id)
}

func (c *Controller) UpdateAssignment(ctx context.Context, id string, resource *Assignment) error {
	return api.Update(c.Client(), ctx, AssignmentOpts, resource, id)
}

func (c *Controller) DeleteAssignment(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, AssignmentOpts, id)
}
