// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var AssignmentOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/interfaces/assignment/add_item", Method: "POST"},
	Read:        api.Endpoint{Path: "/interfaces/assignment/get_item", Method: "GET"},
	Update:      api.Endpoint{Path: "/interfaces/assignment/set_item", Method: "POST"},
	Delete:      api.Endpoint{Path: "/interfaces/assignment/del_item", Method: "POST"},
	Search:      api.Endpoint{Path: "/interfaces/assignment/search_item", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/interfaces/assignment/reconfigure", Method: "POST"},
	Monad:       "interface",
}

// Data structs

type Assignment struct {
	UUID                  string          `json:"uuid,omitempty"`
	Description           string          `json:"descr"`
	Identifier            string          `json:"identifier,omitempty"`
	Icon                  string          `json:"icon,omitempty"`
	Optgroup              string          `json:"optgroup,omitempty"`
	Device                api.SelectedMap `json:"if"`
	Lock                  string          `json:"lock"`
	Enabled               string          `json:"enable"`
	BlockPrivate          string          `json:"blockpriv"`
	BlockBogons           string          `json:"blockbogons"`
	GatewayInterface      string          `json:"gateway_interface"`
	Promiscuous           string          `json:"promisc"`
	SpoofMAC              string          `json:"spoofmac"`
	MTU                   string          `json:"mtu"`
	MSS                   string          `json:"mss"`
	IPv4Mode              api.SelectedMap `json:"type"`
	DHCPHostname          string          `json:"dhcphostname"`
	DHCPAliasAddress      string          `json:"alias-address"`
	DHCPAliasPrefix       string          `json:"alias-subnet"`
	DHCPRejectFrom        string          `json:"dhcprejectfrom"`
	IPv6Mode              api.SelectedMap `json:"type6"`
	DHCP6IAPDLength       string          `json:"dhcp6-ia-pd-len"`
	DHCP6IAPDSendHint     string          `json:"dhcp6-ia-pd-send-hint"`
	DHCP6PrefixOnly       string          `json:"dhcp6prefixonly"`
	DHCP6UseIPv4Interface string          `json:"dhcp6usev4iface"`
	DHCP6VLANPriority     string          `json:"dhcp6vlanprio"`
	Track6Interface       string          `json:"track6-interface"`
	Track6PrefixID        string          `json:"track6-prefix-id"`
	Track6AssociatedPD    string          `json:"track6_assoc_pd"`
	IPv4Address           string          `json:"ipaddr"`
	IPv4Prefix            string          `json:"subnet"`
	IPv4Gateway           string          `json:"gateway"`
	IPv6Address           string          `json:"ipaddrv6"`
	IPv6Prefix            string          `json:"subnetv6"`
	IPv6Gateway           string          `json:"gatewayv6"`
}

// CRUD operations

func (c *Controller) AddAssignment(ctx context.Context, resource *Assignment) (string, error) {
	return api.Add(c.Client(), ctx, AssignmentOpts, resource)
}

func (c *Controller) GetAssignment(ctx context.Context, id string) (*Assignment, error) {
	return api.Get(c.Client(), ctx, AssignmentOpts, &Assignment{}, id)
}

func (c *Controller) SearchAssignment(ctx context.Context) (*api.SearchResponse[Assignment], error) {
	return api.Search[Assignment](c.Client(), ctx, AssignmentOpts.Search)
}

func (c *Controller) UpdateAssignment(ctx context.Context, id string, resource *Assignment) error {
	return api.Update(c.Client(), ctx, AssignmentOpts, resource, id)
}

func (c *Controller) DeleteAssignment(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, AssignmentOpts, id)
}
