// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var BridgeOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/interfaces/bridge_settings/add_item", Method: "POST"},
	Read:        api.Endpoint{Path: "/interfaces/bridge_settings/get_item", Method: "GET"},
	Update:      api.Endpoint{Path: "/interfaces/bridge_settings/set_item", Method: "POST"},
	Delete:      api.Endpoint{Path: "/interfaces/bridge_settings/del_item", Method: "POST"},
	Search:      api.Endpoint{Path: "/interfaces/bridge_settings/search_item", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/interfaces/bridge_settings/reconfigure", Method: "POST"},
	Monad:       "bridge",
}

// Data structs

type Bridge struct {
	UUID             string              `json:"uuid,omitempty"`
	Device           string              `json:"bridgeif"`
	Members          api.SelectedMapList `json:"members"`
	LinkLocal        string              `json:"linklocal"`
	EnableSTP        string              `json:"enablestp"`
	Protocol         api.SelectedMap     `json:"proto"`
	STPMembers       api.SelectedMapList `json:"stp"`
	MaxAge           string              `json:"maxage"`
	ForwardDelay     string              `json:"fwdelay"`
	HoldCount        string              `json:"holdcnt"`
	MaxAddresses     string              `json:"maxaddr"`
	Timeout          string              `json:"timeout"`
	Span             api.SelectedMap     `json:"span"`
	Edge             api.SelectedMapList `json:"edge"`
	AutoEdge         api.SelectedMapList `json:"autoedge"`
	PointToPoint     api.SelectedMapList `json:"ptp"`
	AutoPointToPoint api.SelectedMapList `json:"autoptp"`
	Static           api.SelectedMapList `json:"static"`
	Private          api.SelectedMapList `json:"private"`
	Description      string              `json:"descr"`
}

// CRUD operations

func (c *Controller) AddBridge(ctx context.Context, resource *Bridge) (string, error) {
	return api.Add(c.Client(), ctx, BridgeOpts, resource)
}

func (c *Controller) GetBridge(ctx context.Context, id string) (*Bridge, error) {
	return api.Get(c.Client(), ctx, BridgeOpts, &Bridge{}, id)
}

func (c *Controller) SearchBridge(ctx context.Context) (*api.SearchResponse[Bridge], error) {
	return api.Search[Bridge](c.Client(), ctx, BridgeOpts.Search)
}

func (c *Controller) UpdateBridge(ctx context.Context, id string, resource *Bridge) error {
	return api.Update(c.Client(), ctx, BridgeOpts, resource, id)
}

func (c *Controller) DeleteBridge(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, BridgeOpts, id)
}
