// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var GifOpts = api.ReqOpts{
	AddEndpoint:         "/interfaces/gif_settings/add_item",
	GetEndpoint:         "/interfaces/gif_settings/get_item",
	UpdateEndpoint:      "/interfaces/gif_settings/set_item",
	DeleteEndpoint:      "/interfaces/gif_settings/del_item",
	SearchEndpoint:      "/interfaces/gif_settings/search_item",
	ReconfigureEndpoint: "/interfaces/gif_settings/reconfigure",
	Monad:               "gif",
}

// Data structs

type Gif struct {
	UUID                string `json:"uuid,omitempty"`
	LocalAddress        string `json:"local-addr"`
	Interface           string `json:"if,omitempty"`
	IPAddress           string `json:"ipaddr,omitempty"`
	Device              string `json:"gifif,omitempty"`
	RemoteAddress       string `json:"remote-addr"`
	TunnelLocalAddress  string `json:"tunnel-local-addr"`
	TunnelRemoteAddress string `json:"tunnel-remote-addr"`
	TunnelRemotePrefix  string `json:"tunnel-remote-net"`
	Description         string `json:"descr"`
	ECNFriendly         string `json:"link1"`
	IngressFiltering    string `json:"link2"`
}

// CRUD operations

func (c *Controller) AddGif(ctx context.Context, resource *Gif) (string, error) {
	return api.Add(c.Client(), ctx, GifOpts, resource)
}

func (c *Controller) GetGif(ctx context.Context, id string) (*Gif, error) {
	return api.Get(c.Client(), ctx, GifOpts, &Gif{}, id)
}

func (c *Controller) SearchGif(ctx context.Context) (*api.SearchResponse[Gif], error) {
	return api.Search[Gif](c.Client(), ctx, GifOpts.SearchEndpoint)
}

func (c *Controller) UpdateGif(ctx context.Context, id string, resource *Gif) error {
	return api.Update(c.Client(), ctx, GifOpts, resource, id)
}

func (c *Controller) DeleteGif(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, GifOpts, id)
}
