// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var GreOpts = api.ReqOpts{
	AddEndpoint:         "/interfaces/gre_settings/add_item",
	GetEndpoint:         "/interfaces/gre_settings/get_item",
	UpdateEndpoint:      "/interfaces/gre_settings/set_item",
	DeleteEndpoint:      "/interfaces/gre_settings/del_item",
	SearchEndpoint:      "/interfaces/gre_settings/search_item",
	ReconfigureEndpoint: "/interfaces/gre_settings/reconfigure",
	Monad:               "gre",
}

// Data structs

type Gre struct {
	UUID                string `json:"uuid,omitempty"`
	LocalAddress        string `json:"local-addr"`
	Interface           string `json:"if,omitempty"`
	IPAddress           string `json:"ipaddr,omitempty"`
	Device              string `json:"greif,omitempty"`
	RemoteAddress       string `json:"remote-addr"`
	TunnelLocalAddress  string `json:"tunnel-local-addr"`
	TunnelRemoteAddress string `json:"tunnel-remote-addr"`
	TunnelRemotePrefix  string `json:"tunnel-remote-net"`
	Description         string `json:"descr"`
}

// CRUD operations

func (c *Controller) AddGre(ctx context.Context, resource *Gre) (string, error) {
	return api.Add(c.Client(), ctx, GreOpts, resource)
}

func (c *Controller) GetGre(ctx context.Context, id string) (*Gre, error) {
	return api.Get(c.Client(), ctx, GreOpts, &Gre{}, id)
}

func (c *Controller) SearchGre(ctx context.Context) (*api.SearchResponse[Gre], error) {
	return api.Search[Gre](c.Client(), ctx, GreOpts.SearchEndpoint)
}

func (c *Controller) UpdateGre(ctx context.Context, id string, resource *Gre) error {
	return api.Update(c.Client(), ctx, GreOpts, resource, id)
}

func (c *Controller) DeleteGre(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, GreOpts, id)
}
