// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package interfaces

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

// GreUtilityGetIfOptions executes the GetIfOptions RPC call of the GreUtility controller
func (c *Controller) GreUtilityGetIfOptions(ctx context.Context) (*map[string]interface{}, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/interfaces/gre_settings/get_if_options", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &map[string]interface{}{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("getIfOptions call failed: %w", err)
	}
	return result, nil
}
