// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var LaggOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/interfaces/lagg_settings/add_item", Method: "POST"},
	Read:        api.Endpoint{Path: "/interfaces/lagg_settings/get_item", Method: "GET"},
	Update:      api.Endpoint{Path: "/interfaces/lagg_settings/set_item", Method: "POST"},
	Delete:      api.Endpoint{Path: "/interfaces/lagg_settings/del_item", Method: "POST"},
	Search:      api.Endpoint{Path: "/interfaces/lagg_settings/search_item", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/interfaces/lagg_settings/reconfigure", Method: "POST"},
	Monad:       "lagg",
}

// Data structs

type Lagg struct {
	UUID            string              `json:"uuid,omitempty"`
	Device          string              `json:"laggif"`
	Members         api.SelectedMapList `json:"members"`
	PrimaryMember   api.SelectedMap     `json:"primary_member,omitempty"`
	Protocol        api.SelectedMap     `json:"proto"`
	LACPFastTimeout string              `json:"lacp_fast_timeout"`
	UseFlowID       api.SelectedMap     `json:"use_flowid"`
	HashLayers      api.SelectedMapList `json:"lagghash"`
	LACPStrict      api.SelectedMap     `json:"lacp_strict"`
	MTU             string              `json:"mtu"`
	Description     string              `json:"descr"`
}

// CRUD operations

func (c *Controller) AddLagg(ctx context.Context, resource *Lagg) (string, error) {
	return api.Add(c.Client(), ctx, LaggOpts, resource)
}

func (c *Controller) GetLagg(ctx context.Context, id string) (*Lagg, error) {
	return api.Get(c.Client(), ctx, LaggOpts, &Lagg{}, id)
}

func (c *Controller) SearchLagg(ctx context.Context) (*api.SearchResponse[Lagg], error) {
	return api.Search[Lagg](c.Client(), ctx, LaggOpts.Search)
}

func (c *Controller) UpdateLagg(ctx context.Context, id string, resource *Lagg) error {
	return api.Update(c.Client(), ctx, LaggOpts, resource, id)
}

func (c *Controller) DeleteLagg(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, LaggOpts, id)
}
