// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var LoopbackOpts = api.ReqOpts{
	AddEndpoint:         "/interfaces/loopback_settings/add_item",
	GetEndpoint:         "/interfaces/loopback_settings/get_item",
	UpdateEndpoint:      "/interfaces/loopback_settings/set_item",
	DeleteEndpoint:      "/interfaces/loopback_settings/del_item",
	SearchEndpoint:      "/interfaces/loopback_settings/search_item",
	ReconfigureEndpoint: "/interfaces/loopback_settings/reconfigure",
	Monad:               "loopback",
}

// Data structs

type Loopback struct {
	UUID        string `json:"uuid,omitempty"`
	DeviceID    string `json:"deviceId,omitempty"`
	Description string `json:"description"`
}

// CRUD operations

func (c *Controller) AddLoopback(ctx context.Context, resource *Loopback) (string, error) {
	return api.Add(c.Client(), ctx, LoopbackOpts, resource)
}

func (c *Controller) GetLoopback(ctx context.Context, id string) (*Loopback, error) {
	return api.Get(c.Client(), ctx, LoopbackOpts, &Loopback{}, id)
}

func (c *Controller) SearchLoopback(ctx context.Context) (*api.SearchResponse[Loopback], error) {
	return api.Search[Loopback](c.Client(), ctx, LoopbackOpts.SearchEndpoint)
}

func (c *Controller) UpdateLoopback(ctx context.Context, id string, resource *Loopback) error {
	return api.Update(c.Client(), ctx, LoopbackOpts, resource, id)
}

func (c *Controller) DeleteLoopback(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, LoopbackOpts, id)
}
