// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var NeighborOpts = api.ReqOpts{
	AddEndpoint:         "/interfaces/neighbor_settings/add_item",
	GetEndpoint:         "/interfaces/neighbor_settings/get_item",
	UpdateEndpoint:      "/interfaces/neighbor_settings/set_item",
	DeleteEndpoint:      "/interfaces/neighbor_settings/del_item",
	SearchEndpoint:      "/interfaces/neighbor_settings/search_item",
	ReconfigureEndpoint: "/interfaces/neighbor_settings/reconfigure",
	Monad:               "neighbor",
}

// Data structs

type Neighbor struct {
	UUID        string `json:"uuid,omitempty"`
	MACAddress  string `json:"etheraddr"`
	IPAddress   string `json:"ipaddress"`
	Description string `json:"descr"`
	Origin      string `json:"origin,omitempty"`
}

// CRUD operations

func (c *Controller) AddNeighbor(ctx context.Context, resource *Neighbor) (string, error) {
	return api.Add(c.Client(), ctx, NeighborOpts, resource)
}

func (c *Controller) GetNeighbor(ctx context.Context, id string) (*Neighbor, error) {
	return api.Get(c.Client(), ctx, NeighborOpts, &Neighbor{}, id)
}

func (c *Controller) SearchNeighbor(ctx context.Context) (*api.SearchResponse[Neighbor], error) {
	return api.Search[Neighbor](c.Client(), ctx, NeighborOpts.SearchEndpoint)
}

func (c *Controller) UpdateNeighbor(ctx context.Context, id string, resource *Neighbor) error {
	return api.Update(c.Client(), ctx, NeighborOpts, resource, id)
}

func (c *Controller) DeleteNeighbor(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, NeighborOpts, id)
}
