// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package interfaces

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type InterfaceSettings struct {
	DisableChecksumOffloading     string          `json:"disablechecksumoffloading"`
	DisableSegmentationOffloading string          `json:"disablesegmentationoffloading"`
	DisableLargeReceiveOffloading string          `json:"disablelargereceiveoffloading"`
	VLANHardwareFiltering         api.SelectedMap `json:"disablevlanhwfilter"`
	DisableIPv6                   string          `json:"disableipv6"`
	DHCP6NoRelease                string          `json:"dhcp6_norelease"`
	DHCP6Debug                    string          `json:"dhcp6_debug"`
	DHCP6DUID                     string          `json:"dhcp6_duid"`
	DHCP6RATimeout                string          `json:"dhcp6_ratimeout"`
}

type SettingsGetResult struct {
	Settings InterfaceSettings `json:"settings"`
	DUIDs    map[string]string `json:"duids"`
}

// SettingsGet executes the Get RPC call of the Settings controller
func (c *Controller) SettingsGet(ctx context.Context) (*SettingsGetResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/interfaces/settings/get",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &SettingsGetResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("get call failed: %w", err)
	}
	return result, nil
}

// SettingsSet executes the Set RPC call of the Settings controller
func (c *Controller) SettingsSet(ctx context.Context, settings *InterfaceSettings) (*api.ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["settings"] = settings

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/interfaces/settings/set",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &api.ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("set call failed: %w", err)
	}
	return result, nil
}

// SettingsReconfigure executes the Reconfigure RPC call of the Settings controller
func (c *Controller) SettingsReconfigure(ctx context.Context) (*api.ReconfigureStatusResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/interfaces/settings/reconfigure",
		Method:          "POST",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &api.ReconfigureStatusResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("reconfigure call failed: %w", err)
	}
	return result, nil
}
