// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var VipOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/interfaces/vip_settings/add_item", Method: "POST"},
	Read:        api.Endpoint{Path: "/interfaces/vip_settings/get_item", Method: "GET"},
	Update:      api.Endpoint{Path: "/interfaces/vip_settings/set_item", Method: "POST"},
	Delete:      api.Endpoint{Path: "/interfaces/vip_settings/del_item", Method: "POST"},
	Search:      api.Endpoint{Path: "/interfaces/vip_settings/search_item", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/interfaces/vip_settings/reconfigure", Method: "POST"},
	Monad:       "vip",
}

// Data structs

type Vip struct {
	UUID              string          `json:"uuid,omitempty"`
	Interface         api.SelectedMap `json:"interface"`
	Mode              api.SelectedMap `json:"mode"`
	Network           string          `json:"network"`
	Gateway           string          `json:"gateway"`
	NoExpand          string          `json:"noexpand"`
	NoBind            string          `json:"nobind"`
	Password          string          `json:"password"`
	VHID              string          `json:"vhid"`
	AdvertisementBase string          `json:"advbase"`
	AdvertisementSkew string          `json:"advskew"`
	PeerIPv4          string          `json:"peer"`
	PeerIPv6          string          `json:"peer6"`
	NoSync            string          `json:"nosync"`
	Address           string          `json:"address,omitempty"`
	VHIDText          string          `json:"vhid_txt,omitempty"`
	Description       string          `json:"descr"`
}

// CRUD operations

func (c *Controller) AddVip(ctx context.Context, resource *Vip) (string, error) {
	return api.Add(c.Client(), ctx, VipOpts, resource)
}

func (c *Controller) GetVip(ctx context.Context, id string) (*Vip, error) {
	return api.Get(c.Client(), ctx, VipOpts, &Vip{}, id)
}

func (c *Controller) SearchVip(ctx context.Context) (*api.SearchResponse[Vip], error) {
	return api.Search[Vip](c.Client(), ctx, VipOpts.Search)
}

func (c *Controller) UpdateVip(ctx context.Context, id string, resource *Vip) error {
	return api.Update(c.Client(), ctx, VipOpts, resource, id)
}

func (c *Controller) DeleteVip(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, VipOpts, id)
}
