// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package interfaces

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type UnusedVHIDResult struct {
	VHID   int    `json:"vhid,omitempty"`
	Status string `json:"status"`
}

// VipUtilityGetUnusedVHID executes the GetUnusedVHID RPC call of the VipUtility controller
func (c *Controller) VipUtilityGetUnusedVHID(ctx context.Context) (*UnusedVHIDResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/interfaces/vip_settings/get_unused_vhid",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &UnusedVHIDResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("getUnusedVHID call failed: %w", err)
	}
	return result, nil
}
