// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var VlanOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/interfaces/vlan_settings/add_item", Method: "POST"},
	Read:        api.Endpoint{Path: "/interfaces/vlan_settings/get_item", Method: "GET"},
	Update:      api.Endpoint{Path: "/interfaces/vlan_settings/set_item", Method: "POST"},
	Delete:      api.Endpoint{Path: "/interfaces/vlan_settings/del_item", Method: "POST"},
	Search:      api.Endpoint{Path: "/interfaces/vlan_settings/search_item", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/interfaces/vlan_settings/reconfigure", Method: "POST"},
	Monad:       "vlan",
}

// Data structs

type Vlan struct {
	UUID        string          `json:"uuid,omitempty"`
	Description string          `json:"descr"`
	Tag         string          `json:"tag"`
	Priority    api.SelectedMap `json:"pcp"`
	Protocol    api.SelectedMap `json:"proto"`
	Parent      api.SelectedMap `json:"if"`
	Device      string          `json:"vlanif"`
}

// CRUD operations

func (c *Controller) AddVlan(ctx context.Context, resource *Vlan) (string, error) {
	return api.Add(c.Client(), ctx, VlanOpts, resource)
}

func (c *Controller) GetVlan(ctx context.Context, id string) (*Vlan, error) {
	return api.Get(c.Client(), ctx, VlanOpts, &Vlan{}, id)
}

func (c *Controller) SearchVlan(ctx context.Context) (*api.SearchResponse[Vlan], error) {
	return api.Search[Vlan](c.Client(), ctx, VlanOpts.Search)
}

func (c *Controller) UpdateVlan(ctx context.Context, id string, resource *Vlan) error {
	return api.Update(c.Client(), ctx, VlanOpts, resource, id)
}

func (c *Controller) DeleteVlan(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, VlanOpts, id)
}
