// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package interfaces

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var VxlanOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/interfaces/vxlan_settings/add_item", Method: "POST"},
	Read:        api.Endpoint{Path: "/interfaces/vxlan_settings/get_item", Method: "GET"},
	Update:      api.Endpoint{Path: "/interfaces/vxlan_settings/set_item", Method: "POST"},
	Delete:      api.Endpoint{Path: "/interfaces/vxlan_settings/del_item", Method: "POST"},
	Search:      api.Endpoint{Path: "/interfaces/vxlan_settings/search_item", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/interfaces/vxlan_settings/reconfigure", Method: "POST"},
	Monad:       "vxlan",
}

// Data structs

type Vxlan struct {
	UUID              string          `json:"uuid,omitempty"`
	DeviceID          string          `json:"deviceId,omitempty"`
	VNI               string          `json:"vxlanid"`
	LocalAddress      string          `json:"vxlanlocal"`
	LocalPort         string          `json:"vxlanlocalport"`
	RemoteAddress     string          `json:"vxlanremote"`
	RemotePort        string          `json:"vxlanremoteport"`
	MulticastGroup    string          `json:"vxlangroup"`
	PhysicalInterface api.SelectedMap `json:"vxlandev"`
}

// CRUD operations

func (c *Controller) AddVxlan(ctx context.Context, resource *Vxlan) (string, error) {
	return api.Add(c.Client(), ctx, VxlanOpts, resource)
}

func (c *Controller) GetVxlan(ctx context.Context, id string) (*Vxlan, error) {
	return api.Get(c.Client(), ctx, VxlanOpts, &Vxlan{}, id)
}

func (c *Controller) SearchVxlan(ctx context.Context) (*api.SearchResponse[Vxlan], error) {
	return api.Search[Vxlan](c.Client(), ctx, VxlanOpts.Search)
}

func (c *Controller) UpdateVxlan(ctx context.Context, id string, resource *Vxlan) error {
	return api.Update(c.Client(), ctx, VxlanOpts, resource, id)
}

func (c *Controller) DeleteVxlan(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, VxlanOpts, id)
}
