// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package bind

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var AclOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/bind/acl/add_acl", Method: "POST"},
	Read:        api.Endpoint{Path: "/bind/acl/get_acl", Method: "GET"},
	Update:      api.Endpoint{Path: "/bind/acl/set_acl", Method: "POST"},
	Delete:      api.Endpoint{Path: "/bind/acl/del_acl", Method: "POST"},
	Search:      api.Endpoint{Path: "/bind/acl/search_acl", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/bind/service/reload", Method: "POST"},
	Monad:       "acl",
}

// Data structs

type Acl struct {
	Name     string              `json:"name"`
	Enabled  string              `json:"enabled"`
	Networks api.SelectedMapList `json:"networks"`
}

// CRUD operations

func (c *Controller) AddAcl(ctx context.Context, resource *Acl) (string, error) {
	return api.Add(c.Client(), ctx, AclOpts, resource)
}

func (c *Controller) GetAcl(ctx context.Context, id string) (*Acl, error) {
	return api.Get(c.Client(), ctx, AclOpts, &Acl{}, id)
}

func (c *Controller) SearchAcl(ctx context.Context) (*api.SearchResponse[Acl], error) {
	return api.Search[Acl](c.Client(), ctx, AclOpts.Search)
}

func (c *Controller) UpdateAcl(ctx context.Context, id string, resource *Acl) error {
	return api.Update(c.Client(), ctx, AclOpts, resource, id)
}

func (c *Controller) DeleteAcl(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, AclOpts, id)
}
