// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package bind

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type DNSSECKey struct {
	File      string `json:"file"`
	KeyTag    string `json:"key_tag"`
	Algorithm string `json:"algorithm"`
	Flags     string `json:"flags"`
	Role      string `json:"role"`
}

type DNSSECStatus struct {
	Zone          string            `json:"zone"`
	View          string            `json:"view"`
	DSRecords     []string          `json:"ds_records"`
	Keys          []DNSSECKey       `json:"keys"`
	RNDCStatus    map[string]string `json:"rndc_status"`
	Secure        bool              `json:"secure"`
	InlineSigning bool              `json:"inline_signing"`
	Error         string            `json:"error,omitempty"`
}

// DNSSECStatus executes the Status RPC call of the DNSSEC controller
func (c *Controller) DNSSECStatus(ctx context.Context, zone string, uuid string) (*DNSSECStatus, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["zone"] = zone

	bodyParams["uuid"] = uuid

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/bind/general/dnssec_status", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &DNSSECStatus{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("status call failed: %w", err)
	}
	return result, nil
}
