// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package bind

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var ForwardDomainOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/bind/domain/add_forward_domain", Method: "POST"},
	Read:        api.Endpoint{Path: "/bind/domain/get_domain", Method: "GET"},
	Update:      api.Endpoint{Path: "/bind/domain/set_domain", Method: "POST"},
	Delete:      api.Endpoint{Path: "/bind/domain/del_domain", Method: "POST"},
	Search:      api.Endpoint{Path: "/bind/domain/search_forward_domain", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/bind/service/reload", Method: "POST"},
	Monad:       "domain",
}

// Data structs

type ForwardDomain struct {
	View           api.SelectedMap     `json:"view"`
	DomainName     string              `json:"domainname"`
	Enabled        string              `json:"enabled"`
	ForwardServers api.SelectedMapList `json:"forwardserver"`
	AllowQuery     api.SelectedMapList `json:"allowquery"`
}

// CRUD operations

func (c *Controller) AddForwardDomain(ctx context.Context, resource *ForwardDomain) (string, error) {
	return api.Add(c.Client(), ctx, ForwardDomainOpts, resource)
}

func (c *Controller) GetForwardDomain(ctx context.Context, id string) (*ForwardDomain, error) {
	return api.Get(c.Client(), ctx, ForwardDomainOpts, &ForwardDomain{}, id)
}

func (c *Controller) SearchForwardDomain(ctx context.Context) (*api.SearchResponse[ForwardDomain], error) {
	return api.Search[ForwardDomain](c.Client(), ctx, ForwardDomainOpts.Search)
}

func (c *Controller) UpdateForwardDomain(ctx context.Context, id string, resource *ForwardDomain) error {
	return api.Update(c.Client(), ctx, ForwardDomainOpts, resource, id)
}

func (c *Controller) DeleteForwardDomain(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, ForwardDomainOpts, id)
}
