// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package bind

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var InViewDomainOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/bind/domain/add_in_view_domain", Method: "POST"},
	Read:        api.Endpoint{Path: "/bind/domain/get_domain", Method: "GET"},
	Update:      api.Endpoint{Path: "/bind/domain/set_domain", Method: "POST"},
	Delete:      api.Endpoint{Path: "/bind/domain/del_domain", Method: "POST"},
	Search:      api.Endpoint{Path: "/bind/domain/search_in_view_domain", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/bind/service/reload", Method: "POST"},
	Monad:       "domain",
}

// Data structs

type InViewDomain struct {
	View       api.SelectedMap `json:"view"`
	DomainName string          `json:"domainname"`
	Enabled    string          `json:"enabled"`
	SourceView api.SelectedMap `json:"inview"`
}

// CRUD operations

func (c *Controller) AddInViewDomain(ctx context.Context, resource *InViewDomain) (string, error) {
	return api.Add(c.Client(), ctx, InViewDomainOpts, resource)
}

func (c *Controller) GetInViewDomain(ctx context.Context, id string) (*InViewDomain, error) {
	return api.Get(c.Client(), ctx, InViewDomainOpts, &InViewDomain{}, id)
}

func (c *Controller) SearchInViewDomain(ctx context.Context) (*api.SearchResponse[InViewDomain], error) {
	return api.Search[InViewDomain](c.Client(), ctx, InViewDomainOpts.Search)
}

func (c *Controller) UpdateInViewDomain(ctx context.Context, id string, resource *InViewDomain) error {
	return api.Update(c.Client(), ctx, InViewDomainOpts, resource, id)
}

func (c *Controller) DeleteInViewDomain(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, InViewDomainOpts, id)
}
