// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package bind

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var PrimaryDomainOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/bind/domain/add_primary_domain", Method: "POST"},
	Read:        api.Endpoint{Path: "/bind/domain/get_domain", Method: "GET"},
	Update:      api.Endpoint{Path: "/bind/domain/set_domain", Method: "POST"},
	Delete:      api.Endpoint{Path: "/bind/domain/del_domain", Method: "POST"},
	Search:      api.Endpoint{Path: "/bind/domain/search_primary_domain", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/bind/service/reload", Method: "POST"},
	Monad:       "domain",
}

// Data structs

type PrimaryDomain struct {
	UUID              string              `json:"uuid,omitempty"`
	View              api.SelectedMap     `json:"view"`
	DomainName        string              `json:"domainname"`
	Enabled           string              `json:"enabled"`
	AllowTransfer     api.SelectedMapList `json:"allowtransfer"`
	AllowRndcTransfer string              `json:"allowrndctransfer"`
	TransferKey       api.SelectedMap     `json:"primarytransferkey"`
	AlsoNotify        api.SelectedMapList `json:"alsonotify"`
	AllowQuery        api.SelectedMapList `json:"allowquery"`
	AllowRndcUpdate   string              `json:"allowrndcupdate"`
	UpdateKeys        api.SelectedMapList `json:"updatekeys"`
	UpdatePolicy      api.SelectedMap     `json:"updatepolicy"`
	DNSSEC            string              `json:"dnssec"`
	Serial            string              `json:"serial,omitempty"`
	TimeToLive        string              `json:"ttl"`
	Refresh           string              `json:"refresh"`
	Retry             string              `json:"retry"`
	Expire            string              `json:"expire"`
	Negative          string              `json:"negative"`
	MailAdmin         string              `json:"mailadmin"`
	DnsServer         string              `json:"dnsserver"`
}

// CRUD operations

func (c *Controller) AddPrimaryDomain(ctx context.Context, resource *PrimaryDomain) (string, error) {
	return api.Add(c.Client(), ctx, PrimaryDomainOpts, resource)
}

func (c *Controller) GetPrimaryDomain(ctx context.Context, id string) (*PrimaryDomain, error) {
	return api.Get(c.Client(), ctx, PrimaryDomainOpts, &PrimaryDomain{}, id)
}

func (c *Controller) SearchPrimaryDomain(ctx context.Context) (*api.SearchResponse[PrimaryDomain], error) {
	return api.Search[PrimaryDomain](c.Client(), ctx, PrimaryDomainOpts.Search)
}

func (c *Controller) UpdatePrimaryDomain(ctx context.Context, id string, resource *PrimaryDomain) error {
	return api.Update(c.Client(), ctx, PrimaryDomainOpts, resource, id)
}

func (c *Controller) DeletePrimaryDomain(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, PrimaryDomainOpts, id)
}
