// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package bind

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var RecordOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/bind/record/add_record", Method: "POST"},
	Read:        api.Endpoint{Path: "/bind/record/get_record", Method: "GET"},
	Update:      api.Endpoint{Path: "/bind/record/set_record", Method: "POST"},
	Delete:      api.Endpoint{Path: "/bind/record/del_record", Method: "POST"},
	Search:      api.Endpoint{Path: "/bind/record/search_record", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/bind/service/reconfigure", Method: "POST"},
	Monad:       "record",
}

// Data structs

type Record struct {
	Domain  api.SelectedMap `json:"domain"`
	Enabled string          `json:"enabled"`
	Name    string          `json:"name"`
	Type    api.SelectedMap `json:"type"`
	Value   string          `json:"value"`
}

// CRUD operations

func (c *Controller) AddRecord(ctx context.Context, resource *Record) (string, error) {
	return api.Add(c.Client(), ctx, RecordOpts, resource)
}

func (c *Controller) GetRecord(ctx context.Context, id string) (*Record, error) {
	return api.Get(c.Client(), ctx, RecordOpts, &Record{}, id)
}

func (c *Controller) SearchRecord(ctx context.Context) (*api.SearchResponse[Record], error) {
	return api.Search[Record](c.Client(), ctx, RecordOpts.Search)
}

func (c *Controller) UpdateRecord(ctx context.Context, id string, resource *Record) error {
	return api.Update(c.Client(), ctx, RecordOpts, resource, id)
}

func (c *Controller) DeleteRecord(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, RecordOpts, id)
}
