// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package bind

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var SecondaryDomainOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/bind/domain/add_secondary_domain", Method: "POST"},
	Read:        api.Endpoint{Path: "/bind/domain/get_domain", Method: "GET"},
	Update:      api.Endpoint{Path: "/bind/domain/set_domain", Method: "POST"},
	Delete:      api.Endpoint{Path: "/bind/domain/del_domain", Method: "POST"},
	Search:      api.Endpoint{Path: "/bind/domain/search_secondary_domain", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/bind/service/reload", Method: "POST"},
	Monad:       "domain",
}

// Data structs

type SecondaryDomain struct {
	View                 api.SelectedMap     `json:"view"`
	DomainName           string              `json:"domainname"`
	Enabled              string              `json:"enabled"`
	PrimaryIP            api.SelectedMapList `json:"primaryip"`
	AllowNotify          api.SelectedMapList `json:"allownotifysecondary"`
	TransferKeyAlgorithm api.SelectedMap     `json:"transferkeyalgo"`
	TransferKeyName      string              `json:"transferkeyname"`
	TransferKey          string              `json:"transferkey"`
	AllowTransfer        api.SelectedMapList `json:"allowtransfer"`
	AllowQuery           api.SelectedMapList `json:"allowquery"`
}

// CRUD operations

func (c *Controller) AddSecondaryDomain(ctx context.Context, resource *SecondaryDomain) (string, error) {
	return api.Add(c.Client(), ctx, SecondaryDomainOpts, resource)
}

func (c *Controller) GetSecondaryDomain(ctx context.Context, id string) (*SecondaryDomain, error) {
	return api.Get(c.Client(), ctx, SecondaryDomainOpts, &SecondaryDomain{}, id)
}

func (c *Controller) SearchSecondaryDomain(ctx context.Context) (*api.SearchResponse[SecondaryDomain], error) {
	return api.Search[SecondaryDomain](c.Client(), ctx, SecondaryDomainOpts.Search)
}

func (c *Controller) UpdateSecondaryDomain(ctx context.Context, id string, resource *SecondaryDomain) error {
	return api.Update(c.Client(), ctx, SecondaryDomainOpts, resource, id)
}

func (c *Controller) DeleteSecondaryDomain(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, SecondaryDomainOpts, id)
}
