// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package bind

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type GeneralSettings struct {
	Enabled            string              `json:"enabled"`
	DisableIPv6        string              `json:"disablev6"`
	EnableRPZ          string              `json:"enablerpz"`
	ListenIPv4         api.SelectedMapList `json:"listenv4"`
	ListenIPv6         api.SelectedMapList `json:"listenv6"`
	QuerySource        string              `json:"querysource"`
	QuerySourceIPv6    string              `json:"querysourcev6"`
	TransferSource     string              `json:"transfersource"`
	TransferSourceIPv6 string              `json:"transfersourcev6"`
	NotifySource       string              `json:"notifysource"`
	NotifySourceIPv6   string              `json:"notifysourcev6"`
	Port               string              `json:"port"`
	Forwarders         api.SelectedMapList `json:"forwarders"`
	FilterAAAAIPv4     string              `json:"filteraaaav4"`
	FilterAAAAIPv6     string              `json:"filteraaaav6"`
	FilterAAAAACL      api.SelectedMapList `json:"filteraaaaacl"`
	LogSize            string              `json:"logsize"`
	LogLevel           api.SelectedMap     `json:"general_log_level"`
	MaxCacheSize       string              `json:"maxcachesize"`
	Recursion          api.SelectedMapList `json:"recursion"`
	AllowTransfer      api.SelectedMapList `json:"allowtransfer"`
	AllowQuery         api.SelectedMapList `json:"allowquery"`
	DNSSECValidation   api.SelectedMap     `json:"dnssecvalidation"`
	HideHostname       string              `json:"hidehostname"`
	HideVersion        string              `json:"hideversion"`
	DisablePrefetch    string              `json:"disableprefetch"`
	EnableRateLimiting string              `json:"enableratelimiting"`
	RateLimitCount     string              `json:"ratelimitcount"`
	RateLimitExcept    api.SelectedMapList `json:"ratelimitexcept"`
}

type SettingsResponse struct {
	General GeneralSettings `json:"general"`
}

// SettingsGet executes the Get RPC call of the Settings controller
func (c *Controller) SettingsGet(ctx context.Context) (*SettingsResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/bind/general/get", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &SettingsResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("get call failed: %w", err)
	}
	return result, nil
}

// SettingsSet executes the Set RPC call of the Settings controller
func (c *Controller) SettingsSet(ctx context.Context, general *GeneralSettings) (*api.ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["general"] = general

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/bind/general/set", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &api.ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("set call failed: %w", err)
	}
	return result, nil
}
