// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package bind

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type GenerateSecretResponse struct {
	Secret string `json:"secret"`
}

// TSIGGenerateSecret executes the GenerateSecret RPC call of the TSIG controller
func (c *Controller) TSIGGenerateSecret(ctx context.Context) (*GenerateSecretResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/bind/tsig/generate_secret", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &GenerateSecretResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("generateSecret call failed: %w", err)
	}
	return result, nil
}
