// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package bind

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var TsigKeyOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/bind/tsig/add_key", Method: "POST"},
	Read:        api.Endpoint{Path: "/bind/tsig/get_key", Method: "GET"},
	Update:      api.Endpoint{Path: "/bind/tsig/set_key", Method: "POST"},
	Delete:      api.Endpoint{Path: "/bind/tsig/del_key", Method: "POST"},
	Search:      api.Endpoint{Path: "/bind/tsig/search_key", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/bind/service/reconfigure", Method: "POST"},
	Monad:       "key",
}

// Data structs

type TsigKey struct {
	Enabled   string          `json:"enabled"`
	Name      string          `json:"name"`
	Algorithm api.SelectedMap `json:"algorithm"`
	Secret    string          `json:"secret"`
}

// CRUD operations

func (c *Controller) AddTsigKey(ctx context.Context, resource *TsigKey) (string, error) {
	return api.Add(c.Client(), ctx, TsigKeyOpts, resource)
}

func (c *Controller) GetTsigKey(ctx context.Context, id string) (*TsigKey, error) {
	return api.Get(c.Client(), ctx, TsigKeyOpts, &TsigKey{}, id)
}

func (c *Controller) SearchTsigKey(ctx context.Context) (*api.SearchResponse[TsigKey], error) {
	return api.Search[TsigKey](c.Client(), ctx, TsigKeyOpts.Search)
}

func (c *Controller) UpdateTsigKey(ctx context.Context, id string, resource *TsigKey) error {
	return api.Update(c.Client(), ctx, TsigKeyOpts, resource, id)
}

func (c *Controller) DeleteTsigKey(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, TsigKeyOpts, id)
}
