// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package bind

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var ViewOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/bind/view/add_view", Method: "POST"},
	Read:        api.Endpoint{Path: "/bind/view/get_view", Method: "GET"},
	Update:      api.Endpoint{Path: "/bind/view/set_view", Method: "POST"},
	Delete:      api.Endpoint{Path: "/bind/view/del_view", Method: "POST"},
	Search:      api.Endpoint{Path: "/bind/view/search_view", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/bind/service/reconfigure", Method: "POST"},
	Monad:       "view",
}

// Data structs

type View struct {
	Enabled          string              `json:"enabled"`
	Sequence         string              `json:"sequence"`
	Name             string              `json:"name"`
	MatchAny         string              `json:"matchany"`
	MatchClients     api.SelectedMapList `json:"matchclients"`
	Recursion        string              `json:"recursion"`
	AllowRecursion   api.SelectedMapList `json:"allowrecursion"`
	AllowQueryAny    string              `json:"allowqueryany"`
	AllowQuery       api.SelectedMapList `json:"allowquery"`
	AllowTransfer    api.SelectedMapList `json:"allowtransfer"`
	Forwarders       api.SelectedMapList `json:"forwarders"`
	DNSSECValidation api.SelectedMap     `json:"dnssecvalidation"`
}

// CRUD operations

func (c *Controller) AddView(ctx context.Context, resource *View) (string, error) {
	return api.Add(c.Client(), ctx, ViewOpts, resource)
}

func (c *Controller) GetView(ctx context.Context, id string) (*View, error) {
	return api.Get(c.Client(), ctx, ViewOpts, &View{}, id)
}

func (c *Controller) SearchView(ctx context.Context) (*api.SearchResponse[View], error) {
	return api.Search[View](c.Client(), ctx, ViewOpts.Search)
}

func (c *Controller) UpdateView(ctx context.Context, id string, resource *View) error {
	return api.Update(c.Client(), ctx, ViewOpts, resource, id)
}

func (c *Controller) DeleteView(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, ViewOpts, id)
}
