// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package haproxy

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var ACLOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/haproxy/settings/add_acl", Method: "POST"},
	Read:        api.Endpoint{Path: "/haproxy/settings/get_acl", Method: "GET"},
	Update:      api.Endpoint{Path: "/haproxy/settings/set_acl", Method: "POST"},
	Delete:      api.Endpoint{Path: "/haproxy/settings/del_acl", Method: "POST"},
	Search:      api.Endpoint{Path: "/haproxy/settings/search_acls", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/haproxy/service/reconfigure", Method: "POST"},
	Monad:       "acl",
}

// Data structs

type ACL struct {
	UUID          string          `json:"uuid,omitempty"`
	Name          string          `json:"name"`
	Description   string          `json:"description,omitempty"`
	Expression    api.SelectedMap `json:"expression"`
	Negate        string          `json:"negate,omitempty"`
	CaseSensitive string          `json:"caseSensitive,omitempty"`
	SSLFCSNI      string          `json:"ssl_fc_sni,omitempty"`
	SSLHelloType  api.SelectedMap `json:"ssl_hello_type,omitempty"`
	CustomACL     string          `json:"custom_acl,omitempty"`
	Value         string          `json:"value,omitempty"`
}

// CRUD operations

func (c *Controller) AddACL(ctx context.Context, resource *ACL) (string, error) {
	return api.Add(c.Client(), ctx, ACLOpts, resource)
}

func (c *Controller) GetACL(ctx context.Context, id string) (*ACL, error) {
	return api.Get(c.Client(), ctx, ACLOpts, &ACL{}, id)
}

func (c *Controller) SearchACL(ctx context.Context) (*api.SearchResponse[ACL], error) {
	return api.Search[ACL](c.Client(), ctx, ACLOpts.Search)
}

func (c *Controller) UpdateACL(ctx context.Context, id string, resource *ACL) error {
	return api.Update(c.Client(), ctx, ACLOpts, resource, id)
}

func (c *Controller) DeleteACL(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, ACLOpts, id)
}
