// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package haproxy

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var ActionOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/haproxy/settings/add_action", Method: "POST"},
	Read:        api.Endpoint{Path: "/haproxy/settings/get_action", Method: "GET"},
	Update:      api.Endpoint{Path: "/haproxy/settings/set_action", Method: "POST"},
	Delete:      api.Endpoint{Path: "/haproxy/settings/del_action", Method: "POST"},
	Search:      api.Endpoint{Path: "/haproxy/settings/search_actions", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/haproxy/service/reconfigure", Method: "POST"},
	Monad:       "action",
}

// Data structs

type Action struct {
	UUID                   string              `json:"uuid,omitempty"`
	Enabled                string              `json:"enabled"`
	Name                   string              `json:"name"`
	Description            string              `json:"description,omitempty"`
	TestType               api.SelectedMap     `json:"testType,omitempty"`
	LinkedACLs             api.SelectedMapList `json:"linkedAcls"`
	Operator               api.SelectedMap     `json:"operator,omitempty"`
	Type                   api.SelectedMap     `json:"type"`
	UseBackend             api.SelectedMap     `json:"use_backend,omitempty"`
	Custom                 string              `json:"custom,omitempty"`
	TCPRequestAction       api.SelectedMap     `json:"tcp_request_action,omitempty"`
	TCPRequestOption       string              `json:"tcp_request_option,omitempty"`
	TCPRequestInspectDelay string              `json:"tcp_request_inspect_delay,omitempty"`
}

// CRUD operations

func (c *Controller) AddAction(ctx context.Context, resource *Action) (string, error) {
	return api.Add(c.Client(), ctx, ActionOpts, resource)
}

func (c *Controller) GetAction(ctx context.Context, id string) (*Action, error) {
	return api.Get(c.Client(), ctx, ActionOpts, &Action{}, id)
}

func (c *Controller) SearchAction(ctx context.Context) (*api.SearchResponse[Action], error) {
	return api.Search[Action](c.Client(), ctx, ActionOpts.Search)
}

func (c *Controller) UpdateAction(ctx context.Context, id string, resource *Action) error {
	return api.Update(c.Client(), ctx, ActionOpts, resource, id)
}

func (c *Controller) DeleteAction(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, ActionOpts, id)
}
