// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package haproxy

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var BackendOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/haproxy/settings/add_backend", Method: "POST"},
	Read:        api.Endpoint{Path: "/haproxy/settings/get_backend", Method: "GET"},
	Update:      api.Endpoint{Path: "/haproxy/settings/set_backend", Method: "POST"},
	Delete:      api.Endpoint{Path: "/haproxy/settings/del_backend", Method: "POST"},
	Search:      api.Endpoint{Path: "/haproxy/settings/search_backends", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/haproxy/service/reconfigure", Method: "POST"},
	Monad:       "backend",
}

// Data structs

type Backend struct {
	UUID               string              `json:"uuid,omitempty"`
	Enabled            string              `json:"enabled"`
	Name               string              `json:"name"`
	Description        string              `json:"description,omitempty"`
	Mode               api.SelectedMap     `json:"mode"`
	Algorithm          api.SelectedMap     `json:"algorithm"`
	LinkedServers      api.SelectedMapList `json:"linkedServers"`
	HealthCheckEnabled string              `json:"healthCheckEnabled,omitempty"`
	HealthCheck        api.SelectedMap     `json:"healthCheck,omitempty"`
	CheckInterval      string              `json:"checkInterval,omitempty"`
	CheckDownInterval  string              `json:"checkDownInterval,omitempty"`
	HealthCheckFall    string              `json:"healthCheckFall,omitempty"`
	HealthCheckRise    string              `json:"healthCheckRise,omitempty"`
	CustomOptions      string              `json:"customOptions,omitempty"`
}

// CRUD operations

func (c *Controller) AddBackend(ctx context.Context, resource *Backend) (string, error) {
	return api.Add(c.Client(), ctx, BackendOpts, resource)
}

func (c *Controller) GetBackend(ctx context.Context, id string) (*Backend, error) {
	return api.Get(c.Client(), ctx, BackendOpts, &Backend{}, id)
}

func (c *Controller) SearchBackend(ctx context.Context) (*api.SearchResponse[Backend], error) {
	return api.Search[Backend](c.Client(), ctx, BackendOpts.Search)
}

func (c *Controller) UpdateBackend(ctx context.Context, id string, resource *Backend) error {
	return api.Update(c.Client(), ctx, BackendOpts, resource, id)
}

func (c *Controller) DeleteBackend(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, BackendOpts, id)
}
