// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package haproxy

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var FrontendOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/haproxy/settings/add_frontend", Method: "POST"},
	Read:        api.Endpoint{Path: "/haproxy/settings/get_frontend", Method: "GET"},
	Update:      api.Endpoint{Path: "/haproxy/settings/set_frontend", Method: "POST"},
	Delete:      api.Endpoint{Path: "/haproxy/settings/del_frontend", Method: "POST"},
	Search:      api.Endpoint{Path: "/haproxy/settings/search_frontends", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/haproxy/service/reconfigure", Method: "POST"},
	Monad:       "frontend",
}

// Data structs

type Frontend struct {
	UUID           string              `json:"uuid,omitempty"`
	Enabled        string              `json:"enabled"`
	Name           string              `json:"name"`
	Description    string              `json:"description,omitempty"`
	Bind           api.SelectedMapList `json:"bind"`
	BindOptions    string              `json:"bindOptions,omitempty"`
	Mode           api.SelectedMap     `json:"mode"`
	DefaultBackend api.SelectedMap     `json:"defaultBackend,omitempty"`
	SSLEnabled     string              `json:"ssl_enabled,omitempty"`
	CustomOptions  string              `json:"customOptions,omitempty"`
	LinkedActions  api.SelectedMapList `json:"linkedActions"`
}

// CRUD operations

func (c *Controller) AddFrontend(ctx context.Context, resource *Frontend) (string, error) {
	return api.Add(c.Client(), ctx, FrontendOpts, resource)
}

func (c *Controller) GetFrontend(ctx context.Context, id string) (*Frontend, error) {
	return api.Get(c.Client(), ctx, FrontendOpts, &Frontend{}, id)
}

func (c *Controller) SearchFrontend(ctx context.Context) (*api.SearchResponse[Frontend], error) {
	return api.Search[Frontend](c.Client(), ctx, FrontendOpts.Search)
}

func (c *Controller) UpdateFrontend(ctx context.Context, id string, resource *Frontend) error {
	return api.Update(c.Client(), ctx, FrontendOpts, resource, id)
}

func (c *Controller) DeleteFrontend(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, FrontendOpts, id)
}
