// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package haproxy

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var HealthcheckOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/haproxy/settings/add_healthcheck", Method: "POST"},
	Read:        api.Endpoint{Path: "/haproxy/settings/get_healthcheck", Method: "GET"},
	Update:      api.Endpoint{Path: "/haproxy/settings/set_healthcheck", Method: "POST"},
	Delete:      api.Endpoint{Path: "/haproxy/settings/del_healthcheck", Method: "POST"},
	Search:      api.Endpoint{Path: "/haproxy/settings/search_healthchecks", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/haproxy/service/reconfigure", Method: "POST"},
	Monad:       "healthcheck",
}

// Data structs

type Healthcheck struct {
	UUID          string          `json:"uuid,omitempty"`
	Name          string          `json:"name"`
	Description   string          `json:"description,omitempty"`
	HAPolicy      api.SelectedMap `json:"ha_policy,omitempty"`
	Type          api.SelectedMap `json:"type"`
	Interval      string          `json:"interval,omitempty"`
	SSL           api.SelectedMap `json:"ssl,omitempty"`
	SSLSNI        string          `json:"sslSNI,omitempty"`
	ForceSSL      string          `json:"force_ssl,omitempty"`
	CheckPort     string          `json:"checkport,omitempty"`
	HTTPMethod    api.SelectedMap `json:"http_method,omitempty"`
	HTTPURI       string          `json:"http_uri,omitempty"`
	HTTPHost      string          `json:"http_host,omitempty"`
	TCPSendValue  string          `json:"tcp_sendValue,omitempty"`
	TCPMatchType  api.SelectedMap `json:"tcp_matchType,omitempty"`
	TCPMatchValue string          `json:"tcp_matchValue,omitempty"`
}

// CRUD operations

func (c *Controller) AddHealthcheck(ctx context.Context, resource *Healthcheck) (string, error) {
	return api.Add(c.Client(), ctx, HealthcheckOpts, resource)
}

func (c *Controller) GetHealthcheck(ctx context.Context, id string) (*Healthcheck, error) {
	return api.Get(c.Client(), ctx, HealthcheckOpts, &Healthcheck{}, id)
}

func (c *Controller) SearchHealthcheck(ctx context.Context) (*api.SearchResponse[Healthcheck], error) {
	return api.Search[Healthcheck](c.Client(), ctx, HealthcheckOpts.Search)
}

func (c *Controller) UpdateHealthcheck(ctx context.Context, id string, resource *Healthcheck) error {
	return api.Update(c.Client(), ctx, HealthcheckOpts, resource, id)
}

func (c *Controller) DeleteHealthcheck(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, HealthcheckOpts, id)
}
