// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package haproxy

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var ServerOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/haproxy/settings/add_server", Method: "POST"},
	Read:        api.Endpoint{Path: "/haproxy/settings/get_server", Method: "GET"},
	Update:      api.Endpoint{Path: "/haproxy/settings/set_server", Method: "POST"},
	Delete:      api.Endpoint{Path: "/haproxy/settings/del_server", Method: "POST"},
	Search:      api.Endpoint{Path: "/haproxy/settings/search_servers", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/haproxy/service/reconfigure", Method: "POST"},
	Monad:       "server",
}

// Data structs

type Server struct {
	UUID              string          `json:"uuid,omitempty"`
	Enabled           string          `json:"enabled"`
	Name              string          `json:"name"`
	Description       string          `json:"description,omitempty"`
	HAPolicy          api.SelectedMap `json:"ha_policy,omitempty"`
	Address           string          `json:"address"`
	Port              string          `json:"port,omitempty"`
	CheckPort         string          `json:"checkport,omitempty"`
	Mode              api.SelectedMap `json:"mode"`
	Type              api.SelectedMap `json:"type"`
	SSL               string          `json:"ssl,omitempty"`
	MaxConnections    string          `json:"maxConnections,omitempty"`
	Weight            string          `json:"weight,omitempty"`
	CheckInterval     string          `json:"checkInterval,omitempty"`
	CheckDownInterval string          `json:"checkDownInterval,omitempty"`
	Advanced          string          `json:"advanced,omitempty"`
}

// CRUD operations

func (c *Controller) AddServer(ctx context.Context, resource *Server) (string, error) {
	return api.Add(c.Client(), ctx, ServerOpts, resource)
}

func (c *Controller) GetServer(ctx context.Context, id string) (*Server, error) {
	return api.Get(c.Client(), ctx, ServerOpts, &Server{}, id)
}

func (c *Controller) SearchServer(ctx context.Context) (*api.SearchResponse[Server], error) {
	return api.Search[Server](c.Client(), ctx, ServerOpts.Search)
}

func (c *Controller) UpdateServer(ctx context.Context, id string, resource *Server) error {
	return api.Update(c.Client(), ctx, ServerOpts, resource, id)
}

func (c *Controller) DeleteServer(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, ServerOpts, id)
}
