// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package haproxy

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type GeneralSettings struct {
	Enabled         string `json:"enabled"`
	GracefulStop    string `json:"gracefulStop"`
	HardStopAfter   string `json:"hardStopAfter"`
	CloseSpreadTime string `json:"closeSpreadTime"`
	SeamlessReload  string `json:"seamlessReload"`
}

type Settings struct {
	General GeneralSettings `json:"general"`
}

type SettingsResponse struct {
	HAProxy Settings `json:"haproxy"`
}

// SettingsGet executes the Get RPC call of the Settings controller
func (c *Controller) SettingsGet(ctx context.Context) (*SettingsResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/haproxy/settings/get", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &SettingsResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("get call failed: %w", err)
	}
	return result, nil
}

// SettingsSet executes the Set RPC call of the Settings controller
func (c *Controller) SettingsSet(ctx context.Context, haproxy *Settings) (*api.ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["haproxy"] = haproxy

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/haproxy/settings/set", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &api.ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("set call failed: %w", err)
	}
	return result, nil
}
