// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type FRRGeneralResponse struct {
	General FRRGeneralSettings `json:"general"`
}

type FRRGeneralSettings struct {
	Enabled       string          `json:"enabled"`
	Profile       api.SelectedMap `json:"profile"`
	EnableCARP    string          `json:"enablecarp"`
	EnableSyslog  string          `json:"enablesyslog"`
	EnableSNMP    string          `json:"enablesnmp"`
	SyslogLevel   api.SelectedMap `json:"sysloglevel"`
	FirewallRules string          `json:"fwrules"`
}

// FRRGeneralGet executes the Get RPC call of the FRRGeneral controller
func (c *Controller) FRRGeneralGet(ctx context.Context) (*FRRGeneralResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/quagga/general/get", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &FRRGeneralResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("get call failed: %w", err)
	}
	return result, nil
}

// FRRGeneralSet executes the Set RPC call of the FRRGeneral controller
func (c *Controller) FRRGeneralSet(ctx context.Context, general *FRRGeneralSettings) (*api.ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["general"] = general

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/quagga/general/set", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &api.ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("set call failed: %w", err)
	}
	return result, nil
}

// FRRGeneralReconfigure executes the Reconfigure RPC call of the FRRGeneral controller
func (c *Controller) FRRGeneralReconfigure(ctx context.Context) (*api.ReconfigureStatusResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/quagga/service/reconfigure", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &api.ReconfigureStatusResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("reconfigure call failed: %w", err)
	}
	return result, nil
}
