// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var OSPFInterfaceOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/quagga/ospfsettings/addInterface", Method: "POST"},
	Read:        api.Endpoint{Path: "/quagga/ospfsettings/getInterface", Method: "GET"},
	Update:      api.Endpoint{Path: "/quagga/ospfsettings/setInterface", Method: "POST"},
	Delete:      api.Endpoint{Path: "/quagga/ospfsettings/delInterface", Method: "POST"},
	Search:      api.Endpoint{Path: "/quagga/ospfsettings/searchInterface", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/quagga/service/reconfigure", Method: "POST"},
	Monad:       "interface",
}

// Data structs

type OSPFInterface struct {
	Enabled            string          `json:"enabled"`
	InterfaceName      api.SelectedMap `json:"interfacename"`
	AuthType           api.SelectedMap `json:"authtype"`
	AuthKey            string          `json:"authkey"`
	AuthKeyID          string          `json:"authkey_id"`
	Area               string          `json:"area"`
	Cost               string          `json:"cost"`
	CostDemoted        string          `json:"cost_demoted"`
	CarpDependOn       api.SelectedMap `json:"carp_depend_on"`
	HelloInterval      string          `json:"hellointerval"`
	DeadInterval       string          `json:"deadinterval"`
	RetransmitInterval string          `json:"retransmitinterval"`
	TransmitDelay      string          `json:"transmitdelay"`
	Priority           string          `json:"priority"`
	BFD                string          `json:"bfd"`
	NetworkType        api.SelectedMap `json:"networktype"`
	P2MPOptions        api.SelectedMap `json:"p2mpoptions"`
}

// CRUD operations

func (c *Controller) AddOSPFInterface(ctx context.Context, resource *OSPFInterface) (string, error) {
	return api.Add(c.Client(), ctx, OSPFInterfaceOpts, resource)
}

func (c *Controller) GetOSPFInterface(ctx context.Context, id string) (*OSPFInterface, error) {
	return api.Get(c.Client(), ctx, OSPFInterfaceOpts, &OSPFInterface{}, id)
}

func (c *Controller) SearchOSPFInterface(ctx context.Context) (*api.SearchResponse[OSPFInterface], error) {
	return api.Search[OSPFInterface](c.Client(), ctx, OSPFInterfaceOpts.Search)
}

func (c *Controller) UpdateOSPFInterface(ctx context.Context, id string, resource *OSPFInterface) error {
	return api.Update(c.Client(), ctx, OSPFInterfaceOpts, resource, id)
}

func (c *Controller) DeleteOSPFInterface(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, OSPFInterfaceOpts, id)
}
