// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var OSPFNetworkOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/quagga/ospfsettings/addNetwork", Method: "POST"},
	Read:        api.Endpoint{Path: "/quagga/ospfsettings/getNetwork", Method: "GET"},
	Update:      api.Endpoint{Path: "/quagga/ospfsettings/setNetwork", Method: "POST"},
	Delete:      api.Endpoint{Path: "/quagga/ospfsettings/delNetwork", Method: "POST"},
	Search:      api.Endpoint{Path: "/quagga/ospfsettings/searchNetwork", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/quagga/service/reconfigure", Method: "POST"},
	Monad:       "network",
}

// Data structs

type OSPFNetwork struct {
	Enabled       string          `json:"enabled"`
	IPAddress     string          `json:"ipaddr"`
	Area          string          `json:"area"`
	Netmask       string          `json:"netmask"`
	AreaRange     string          `json:"arearange"`
	PrefixListIn  api.SelectedMap `json:"linkedPrefixlistIn"`
	PrefixListOut api.SelectedMap `json:"linkedPrefixlistOut"`
}

// CRUD operations

func (c *Controller) AddOSPFNetwork(ctx context.Context, resource *OSPFNetwork) (string, error) {
	return api.Add(c.Client(), ctx, OSPFNetworkOpts, resource)
}

func (c *Controller) GetOSPFNetwork(ctx context.Context, id string) (*OSPFNetwork, error) {
	return api.Get(c.Client(), ctx, OSPFNetworkOpts, &OSPFNetwork{}, id)
}

func (c *Controller) SearchOSPFNetwork(ctx context.Context) (*api.SearchResponse[OSPFNetwork], error) {
	return api.Search[OSPFNetwork](c.Client(), ctx, OSPFNetworkOpts.Search)
}

func (c *Controller) UpdateOSPFNetwork(ctx context.Context, id string, resource *OSPFNetwork) error {
	return api.Update(c.Client(), ctx, OSPFNetworkOpts, resource, id)
}

func (c *Controller) DeleteOSPFNetwork(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, OSPFNetworkOpts, id)
}
