// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var OSPFRedistributionOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/quagga/ospfsettings/addRedistribution", Method: "POST"},
	Read:        api.Endpoint{Path: "/quagga/ospfsettings/getRedistribution", Method: "GET"},
	Update:      api.Endpoint{Path: "/quagga/ospfsettings/setRedistribution", Method: "POST"},
	Delete:      api.Endpoint{Path: "/quagga/ospfsettings/delRedistribution", Method: "POST"},
	Search:      api.Endpoint{Path: "/quagga/ospfsettings/searchRedistribution", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/quagga/service/reconfigure", Method: "POST"},
	Monad:       "redistribution",
}

// Data structs

type OSPFRedistribution struct {
	Enabled      string          `json:"enabled"`
	Description  string          `json:"description"`
	Redistribute api.SelectedMap `json:"redistribute"`
	RouteMap     api.SelectedMap `json:"linkedRoutemap"`
}

// CRUD operations

func (c *Controller) AddOSPFRedistribution(ctx context.Context, resource *OSPFRedistribution) (string, error) {
	return api.Add(c.Client(), ctx, OSPFRedistributionOpts, resource)
}

func (c *Controller) GetOSPFRedistribution(ctx context.Context, id string) (*OSPFRedistribution, error) {
	return api.Get(c.Client(), ctx, OSPFRedistributionOpts, &OSPFRedistribution{}, id)
}

func (c *Controller) SearchOSPFRedistribution(ctx context.Context) (*api.SearchResponse[OSPFRedistribution], error) {
	return api.Search[OSPFRedistribution](c.Client(), ctx, OSPFRedistributionOpts.Search)
}

func (c *Controller) UpdateOSPFRedistribution(ctx context.Context, id string, resource *OSPFRedistribution) error {
	return api.Update(c.Client(), ctx, OSPFRedistributionOpts, resource, id)
}

func (c *Controller) DeleteOSPFRedistribution(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, OSPFRedistributionOpts, id)
}
