// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type OSPFSettingsData struct {
	Enabled             string              `json:"enabled"`
	CarpDemote          string              `json:"carp_demote"`
	RouterID            string              `json:"routerid"`
	CostReference       string              `json:"costreference"`
	LogAdjacencyChanges string              `json:"logadjacencychanges"`
	Originate           string              `json:"originate"`
	OriginateAlways     string              `json:"originatealways"`
	OriginateMetric     string              `json:"originatemetric"`
	PassiveInterfaces   api.SelectedMapList `json:"passiveinterfaces"`
}

type OSPFSettingsResponse struct {
	OSPF OSPFSettingsData `json:"ospf"`
}

// OSPFSettingsGet executes the Get RPC call of the OSPFSettings controller
func (c *Controller) OSPFSettingsGet(ctx context.Context) (*OSPFSettingsResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/quagga/ospfsettings/get", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &OSPFSettingsResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("get call failed: %w", err)
	}
	return result, nil
}

// OSPFSettingsSet executes the Set RPC call of the OSPFSettings controller
func (c *Controller) OSPFSettingsSet(ctx context.Context, ospf *OSPFSettingsData) (*api.ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["ospf"] = ospf

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/quagga/ospfsettings/set", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &api.ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("set call failed: %w", err)
	}
	return result, nil
}

// OSPFSettingsReconfigure executes the Reconfigure RPC call of the OSPFSettings controller
func (c *Controller) OSPFSettingsReconfigure(ctx context.Context) (*api.ReconfigureStatusResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/quagga/service/reconfigure", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &api.ReconfigureStatusResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("reconfigure call failed: %w", err)
	}
	return result, nil
}
