// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var OSPFRouteMapOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/quagga/ospfsettings/addRoutemap", Method: "POST"},
	Read:        api.Endpoint{Path: "/quagga/ospfsettings/getRoutemap", Method: "GET"},
	Update:      api.Endpoint{Path: "/quagga/ospfsettings/setRoutemap", Method: "POST"},
	Delete:      api.Endpoint{Path: "/quagga/ospfsettings/delRoutemap", Method: "POST"},
	Search:      api.Endpoint{Path: "/quagga/ospfsettings/searchRoutemap", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/quagga/service/reconfigure", Method: "POST"},
	Monad:       "routemap",
}

// Data structs

type OSPFRouteMap struct {
	Enabled    string              `json:"enabled"`
	Name       string              `json:"name"`
	Action     api.SelectedMap     `json:"action"`
	RouteMapID string              `json:"id"`
	PrefixList api.SelectedMapList `json:"match2"`
	Set        string              `json:"set"`
}

// CRUD operations

func (c *Controller) AddOSPFRouteMap(ctx context.Context, resource *OSPFRouteMap) (string, error) {
	return api.Add(c.Client(), ctx, OSPFRouteMapOpts, resource)
}

func (c *Controller) GetOSPFRouteMap(ctx context.Context, id string) (*OSPFRouteMap, error) {
	return api.Get(c.Client(), ctx, OSPFRouteMapOpts, &OSPFRouteMap{}, id)
}

func (c *Controller) SearchOSPFRouteMap(ctx context.Context) (*api.SearchResponse[OSPFRouteMap], error) {
	return api.Search[OSPFRouteMap](c.Client(), ctx, OSPFRouteMapOpts.Search)
}

func (c *Controller) UpdateOSPFRouteMap(ctx context.Context, id string, resource *OSPFRouteMap) error {
	return api.Update(c.Client(), ctx, OSPFRouteMapOpts, resource, id)
}

func (c *Controller) DeleteOSPFRouteMap(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, OSPFRouteMapOpts, id)
}
