// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var OSPF6PrefixListOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/quagga/ospf6settings/addPrefixlist", Method: "POST"},
	Read:        api.Endpoint{Path: "/quagga/ospf6settings/getPrefixlist", Method: "GET"},
	Update:      api.Endpoint{Path: "/quagga/ospf6settings/setPrefixlist", Method: "POST"},
	Delete:      api.Endpoint{Path: "/quagga/ospf6settings/delPrefixlist", Method: "POST"},
	Search:      api.Endpoint{Path: "/quagga/ospf6settings/searchPrefixlist", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/quagga/service/reconfigure", Method: "POST"},
	Monad:       "prefixlist",
}

// Data structs

type OSPF6PrefixList struct {
	Enabled        string          `json:"enabled"`
	Name           string          `json:"name"`
	SequenceNumber string          `json:"seqnumber"`
	Action         api.SelectedMap `json:"action"`
	Network        string          `json:"network"`
}

// CRUD operations

func (c *Controller) AddOSPF6PrefixList(ctx context.Context, resource *OSPF6PrefixList) (string, error) {
	return api.Add(c.Client(), ctx, OSPF6PrefixListOpts, resource)
}

func (c *Controller) GetOSPF6PrefixList(ctx context.Context, id string) (*OSPF6PrefixList, error) {
	return api.Get(c.Client(), ctx, OSPF6PrefixListOpts, &OSPF6PrefixList{}, id)
}

func (c *Controller) SearchOSPF6PrefixList(ctx context.Context) (*api.SearchResponse[OSPF6PrefixList], error) {
	return api.Search[OSPF6PrefixList](c.Client(), ctx, OSPF6PrefixListOpts.Search)
}

func (c *Controller) UpdateOSPF6PrefixList(ctx context.Context, id string, resource *OSPF6PrefixList) error {
	return api.Update(c.Client(), ctx, OSPF6PrefixListOpts, resource, id)
}

func (c *Controller) DeleteOSPF6PrefixList(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, OSPF6PrefixListOpts, id)
}
