// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type OSPF6SettingsData struct {
	Enabled         string `json:"enabled"`
	CarpDemote      string `json:"carp_demote"`
	RouterID        string `json:"routerid"`
	Originate       string `json:"originate"`
	OriginateAlways string `json:"originatealways"`
	OriginateMetric string `json:"originatemetric"`
}

type OSPF6SettingsResponse struct {
	OSPF6 OSPF6SettingsData `json:"ospf6"`
}

// OSPF6SettingsGet executes the Get RPC call of the OSPF6Settings controller
func (c *Controller) OSPF6SettingsGet(ctx context.Context) (*OSPF6SettingsResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/quagga/ospf6settings/get", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &OSPF6SettingsResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("get call failed: %w", err)
	}
	return result, nil
}

// OSPF6SettingsSet executes the Set RPC call of the OSPF6Settings controller
func (c *Controller) OSPF6SettingsSet(ctx context.Context, ospf6 *OSPF6SettingsData) (*api.ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["ospf6"] = ospf6

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/quagga/ospf6settings/set", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &api.ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("set call failed: %w", err)
	}
	return result, nil
}

// OSPF6SettingsReconfigure executes the Reconfigure RPC call of the OSPF6Settings controller
func (c *Controller) OSPF6SettingsReconfigure(ctx context.Context) (*api.ReconfigureStatusResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/quagga/service/reconfigure", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &api.ReconfigureStatusResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("reconfigure call failed: %w", err)
	}
	return result, nil
}
