// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var OSPF6RouteMapOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/quagga/ospf6settings/addRoutemap", Method: "POST"},
	Read:        api.Endpoint{Path: "/quagga/ospf6settings/getRoutemap", Method: "GET"},
	Update:      api.Endpoint{Path: "/quagga/ospf6settings/setRoutemap", Method: "POST"},
	Delete:      api.Endpoint{Path: "/quagga/ospf6settings/delRoutemap", Method: "POST"},
	Search:      api.Endpoint{Path: "/quagga/ospf6settings/searchRoutemap", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/quagga/service/reconfigure", Method: "POST"},
	Monad:       "routemap",
}

// Data structs

type OSPF6RouteMap struct {
	Enabled    string              `json:"enabled"`
	Name       string              `json:"name"`
	Action     api.SelectedMap     `json:"action"`
	RouteMapID string              `json:"id"`
	PrefixList api.SelectedMapList `json:"match2"`
	Set        string              `json:"set"`
}

// CRUD operations

func (c *Controller) AddOSPF6RouteMap(ctx context.Context, resource *OSPF6RouteMap) (string, error) {
	return api.Add(c.Client(), ctx, OSPF6RouteMapOpts, resource)
}

func (c *Controller) GetOSPF6RouteMap(ctx context.Context, id string) (*OSPF6RouteMap, error) {
	return api.Get(c.Client(), ctx, OSPF6RouteMapOpts, &OSPF6RouteMap{}, id)
}

func (c *Controller) SearchOSPF6RouteMap(ctx context.Context) (*api.SearchResponse[OSPF6RouteMap], error) {
	return api.Search[OSPF6RouteMap](c.Client(), ctx, OSPF6RouteMapOpts.Search)
}

func (c *Controller) UpdateOSPF6RouteMap(ctx context.Context, id string, resource *OSPF6RouteMap) error {
	return api.Update(c.Client(), ctx, OSPF6RouteMapOpts, resource, id)
}

func (c *Controller) DeleteOSPF6RouteMap(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, OSPF6RouteMapOpts, id)
}
