// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var OSPF6InterfaceOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/quagga/ospf6settings/addInterface", Method: "POST"},
	Read:        api.Endpoint{Path: "/quagga/ospf6settings/getInterface", Method: "GET"},
	Update:      api.Endpoint{Path: "/quagga/ospf6settings/setInterface", Method: "POST"},
	Delete:      api.Endpoint{Path: "/quagga/ospf6settings/delInterface", Method: "POST"},
	Search:      api.Endpoint{Path: "/quagga/ospf6settings/searchInterface", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/quagga/service/reconfigure", Method: "POST"},
	Monad:       "interface",
}

// Data structs

type OSPF6Interface struct {
	Enabled            string          `json:"enabled"`
	InterfaceName      api.SelectedMap `json:"interfacename"`
	Area               string          `json:"area"`
	Passive            string          `json:"passive"`
	Cost               string          `json:"cost"`
	CostDemoted        string          `json:"cost_demoted"`
	CarpDependOn       api.SelectedMap `json:"carp_depend_on"`
	HelloInterval      string          `json:"hellointerval"`
	DeadInterval       string          `json:"deadinterval"`
	RetransmitInterval string          `json:"retransmitinterval"`
	TransmitDelay      string          `json:"transmitdelay"`
	Priority           string          `json:"priority"`
	BFD                string          `json:"bfd"`
	NetworkType        api.SelectedMap `json:"networktype"`
}

// CRUD operations

func (c *Controller) AddOSPF6Interface(ctx context.Context, resource *OSPF6Interface) (string, error) {
	return api.Add(c.Client(), ctx, OSPF6InterfaceOpts, resource)
}

func (c *Controller) GetOSPF6Interface(ctx context.Context, id string) (*OSPF6Interface, error) {
	return api.Get(c.Client(), ctx, OSPF6InterfaceOpts, &OSPF6Interface{}, id)
}

func (c *Controller) SearchOSPF6Interface(ctx context.Context) (*api.SearchResponse[OSPF6Interface], error) {
	return api.Search[OSPF6Interface](c.Client(), ctx, OSPF6InterfaceOpts.Search)
}

func (c *Controller) UpdateOSPF6Interface(ctx context.Context, id string, resource *OSPF6Interface) error {
	return api.Update(c.Client(), ctx, OSPF6InterfaceOpts, resource, id)
}

func (c *Controller) DeleteOSPF6Interface(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, OSPF6InterfaceOpts, id)
}
