// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package quagga

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var OSPF6RedistributionOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/quagga/ospf6settings/addRedistribution", Method: "POST"},
	Read:        api.Endpoint{Path: "/quagga/ospf6settings/getRedistribution", Method: "GET"},
	Update:      api.Endpoint{Path: "/quagga/ospf6settings/setRedistribution", Method: "POST"},
	Delete:      api.Endpoint{Path: "/quagga/ospf6settings/delRedistribution", Method: "POST"},
	Search:      api.Endpoint{Path: "/quagga/ospf6settings/searchRedistribution", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/quagga/service/reconfigure", Method: "POST"},
	Monad:       "redistribution",
}

// Data structs

type OSPF6Redistribution struct {
	Enabled      string          `json:"enabled"`
	Description  string          `json:"description"`
	Redistribute api.SelectedMap `json:"redistribute"`
	RouteMap     api.SelectedMap `json:"linkedRoutemap"`
}

// CRUD operations

func (c *Controller) AddOSPF6Redistribution(ctx context.Context, resource *OSPF6Redistribution) (string, error) {
	return api.Add(c.Client(), ctx, OSPF6RedistributionOpts, resource)
}

func (c *Controller) GetOSPF6Redistribution(ctx context.Context, id string) (*OSPF6Redistribution, error) {
	return api.Get(c.Client(), ctx, OSPF6RedistributionOpts, &OSPF6Redistribution{}, id)
}

func (c *Controller) SearchOSPF6Redistribution(ctx context.Context) (*api.SearchResponse[OSPF6Redistribution], error) {
	return api.Search[OSPF6Redistribution](c.Client(), ctx, OSPF6RedistributionOpts.Search)
}

func (c *Controller) UpdateOSPF6Redistribution(ctx context.Context, id string, resource *OSPF6Redistribution) error {
	return api.Update(c.Client(), ctx, OSPF6RedistributionOpts, resource, id)
}

func (c *Controller) DeleteOSPF6Redistribution(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, OSPF6RedistributionOpts, id)
}
