// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package routing

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var GatewayGroupOpts = api.ReqOpts{
	AddEndpoint:         "/routing/group_settings/add",
	GetEndpoint:         "/routing/group_settings/get",
	UpdateEndpoint:      "/routing/group_settings/set",
	DeleteEndpoint:      "/routing/group_settings/del",
	SearchEndpoint:      "/routing/group_settings/search",
	ReconfigureEndpoint: "/routing/group_settings/reconfigure",
	Monad:               "gateway_group",
}

// Data structs

type GatewayGroup struct {
	UUID        string              `json:"uuid,omitempty"`
	Name        string              `json:"name"`
	Tier1       api.SelectedMapList `json:"item"`
	Tier2       api.SelectedMapList `json:"item2"`
	Tier3       api.SelectedMapList `json:"item3"`
	Tier4       api.SelectedMapList `json:"item4"`
	Tier5       api.SelectedMapList `json:"item5"`
	Trigger     api.SelectedMap     `json:"trigger"`
	PoolOptions api.SelectedMap     `json:"poolopts"`
	Description string              `json:"descr"`
}

// CRUD operations

func (c *Controller) AddGatewayGroup(ctx context.Context, resource *GatewayGroup) (string, error) {
	return api.Add(c.Client(), ctx, GatewayGroupOpts, resource)
}

func (c *Controller) GetGatewayGroup(ctx context.Context, id string) (*GatewayGroup, error) {
	return api.Get(c.Client(), ctx, GatewayGroupOpts, &GatewayGroup{}, id)
}

func (c *Controller) SearchGatewayGroup(ctx context.Context) (*api.SearchResponse[GatewayGroup], error) {
	return api.Search[GatewayGroup](c.Client(), ctx, GatewayGroupOpts.SearchEndpoint)
}

func (c *Controller) UpdateGatewayGroup(ctx context.Context, id string, resource *GatewayGroup) error {
	return api.Update(c.Client(), ctx, GatewayGroupOpts, resource, id)
}

func (c *Controller) DeleteGatewayGroup(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, GatewayGroupOpts, id)
}
