// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package routing

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var GatewayOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/routing/settings/addGateway", Method: "POST"},
	Read:        api.Endpoint{Path: "/routing/settings/getGateway", Method: "GET"},
	Update:      api.Endpoint{Path: "/routing/settings/setGateway", Method: "POST"},
	Delete:      api.Endpoint{Path: "/routing/settings/delGateway", Method: "POST"},
	Search:      api.Endpoint{Path: "/routing/settings/searchGateway", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/routing/settings/reconfigure", Method: "POST"},
	Monad:       "gateway_item",
}

// Data structs

type Gateway struct {
	UUID                      string          `json:"uuid,omitempty"`
	Disabled                  string          `json:"disabled"`
	Name                      string          `json:"name"`
	Description               string          `json:"descr"`
	Interface                 api.SelectedMap `json:"interface"`
	IPProtocol                api.SelectedMap `json:"ipprotocol"`
	Gateway                   string          `json:"gateway"`
	DefaultGateway            string          `json:"defaultgw"`
	FarGateway                string          `json:"fargw"`
	MonitorDisable            string          `json:"monitor_disable"`
	MonitorNoRoute            string          `json:"monitor_noroute"`
	MonitorKillStates         string          `json:"monitor_killstates"`
	MonitorKillStatesPriority string          `json:"monitor_killstates_priority"`
	Monitor                   string          `json:"monitor"`
	ForceDown                 string          `json:"force_down"`
	NoSync                    string          `json:"nosync"`
	Priority                  string          `json:"priority"`
	Weight                    string          `json:"weight"`
	LatencyLow                string          `json:"latencylow"`
	LatencyHigh               string          `json:"latencyhigh"`
	LossLow                   string          `json:"losslow"`
	LossHigh                  string          `json:"losshigh"`
	Interval                  string          `json:"interval"`
	TimePeriod                string          `json:"time_period"`
	LossInterval              string          `json:"loss_interval"`
	DataLength                string          `json:"data_length"`
}

// CRUD operations

func (c *Controller) AddGateway(ctx context.Context, resource *Gateway) (string, error) {
	return api.Add(c.Client(), ctx, GatewayOpts, resource)
}

func (c *Controller) GetGateway(ctx context.Context, id string) (*Gateway, error) {
	return api.Get(c.Client(), ctx, GatewayOpts, &Gateway{}, id)
}

func (c *Controller) SearchGateway(ctx context.Context) (*api.SearchResponse[Gateway], error) {
	return api.Search[Gateway](c.Client(), ctx, GatewayOpts.Search)
}

func (c *Controller) UpdateGateway(ctx context.Context, id string, resource *Gateway) error {
	return api.Update(c.Client(), ctx, GatewayOpts, resource, id)
}

func (c *Controller) DeleteGateway(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, GatewayOpts, id)
}
