// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package routing

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type GatewayStatusItem struct {
	Name              string `json:"name"`
	Address           string `json:"address"`
	Monitor           string `json:"monitor"`
	Delay             string `json:"delay"`
	StandardDeviation string `json:"stddev"`
	Loss              string `json:"loss"`
	Status            string `json:"status"`
	StatusTranslated  string `json:"status_translated"`
}

type GatewayStatusResponse struct {
	Items  []GatewayStatusItem `json:"items"`
	Status string              `json:"status"`
}

// GatewayStatusGet executes the Get RPC call of the GatewayStatus controller
func (c *Controller) GatewayStatusGet(ctx context.Context) (*GatewayStatusResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:    "/routes/gateway/status",
		Method:          "GET",
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &GatewayStatusResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("get call failed: %w", err)
	}
	return result, nil
}
