// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package auth

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var GroupOpts = api.ReqOpts{
	Create: api.Endpoint{Path: "/auth/group/add", Method: "POST"},
	Read:   api.Endpoint{Path: "/auth/group/get", Method: "GET"},
	Update: api.Endpoint{Path: "/auth/group/set", Method: "POST"},
	Delete: api.Endpoint{Path: "/auth/group/del", Method: "POST"},
	Monad:  "group",
}

// Data structs

type Group struct {
	GroupId        string              `json:"gid"`
	Name           string              `json:"name"`
	Scope          string              `json:"scope,omitempty"`
	Description    string              `json:"description"`
	Privilege      api.SelectedMapList `json:"priv"`
	Member         api.SelectedMap     `json:"member"`
	SourceNetworks api.SelectedMap     `json:"source_networks"`
}

// CRUD operations

func (c *Controller) AddGroup(ctx context.Context, resource *Group) (string, error) {
	return api.Add(c.Client(), ctx, GroupOpts, resource)
}

func (c *Controller) GetGroup(ctx context.Context, id string) (*Group, error) {
	return api.Get(c.Client(), ctx, GroupOpts, &Group{}, id)
}

func (c *Controller) UpdateGroup(ctx context.Context, id string, resource *Group) error {
	return api.Update(c.Client(), ctx, GroupOpts, resource, id)
}

func (c *Controller) DeleteGroup(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, GroupOpts, id)
}
