// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package auth

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type AddApiKeyResult struct {
	Result   string `json:"result"`
	Hostname string `json:"hostname"`
	Key      string `json:"key"`
	Secret   string `json:"secret"`
}

type ApiKeyResult struct {
	Username string `json:"username"`
	Key      string `json:"key"`
	Id       string `json:"id"`
}

type GetAllApiKeysResult struct {
	Total    int            `json:"total"`
	RowCount int            `json:"rowCount"`
	Current  int            `json:"current"`
	Rows     []ApiKeyResult `json:"rows"`
}

// UserAddApiKey executes the AddApiKey RPC call of the User controller
func (c *Controller) UserAddApiKey(ctx context.Context, username string) (*AddApiKeyResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, username)

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/auth/user/add_api_key", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &AddApiKeyResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("addApiKey call failed: %w", err)
	}
	return result, nil
}

// UserDeleteApiKey executes the DeleteApiKey RPC call of the User controller
func (c *Controller) UserDeleteApiKey(ctx context.Context, id string) (*api.ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, id)

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/auth/user/del_api_key", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &api.ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("deleteApiKey call failed: %w", err)
	}
	return result, nil
}

// UserGetAllApiKeys executes the GetAllApiKeys RPC call of the User controller
func (c *Controller) UserGetAllApiKeys(ctx context.Context) (*GetAllApiKeysResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/auth/user/search_api_key", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &GetAllApiKeysResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("getAllApiKeys call failed: %w", err)
	}
	return result, nil
}
