// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package auth

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var UserOpts = api.ReqOpts{
	Create: api.Endpoint{Path: "/auth/user/add", Method: "POST"},
	Read:   api.Endpoint{Path: "/auth/user/get", Method: "GET"},
	Update: api.Endpoint{Path: "/auth/user/set", Method: "POST"},
	Delete: api.Endpoint{Path: "/auth/user/del", Method: "POST"},
	Monad:  "user",
}

// Data structs

type User struct {
	UserId            string              `json:"uid"`
	Name              string              `json:"name"`
	Disabled          string              `json:"disabled"`
	Scope             string              `json:"scope,omitempty"`
	Expires           string              `json:"expires"`
	AuthorizedKeys    string              `json:"authorizedkeys"`
	OtpSeed           string              `json:"otp_seed"`
	Shell             api.SelectedMap     `json:"shell"`
	Password          string              `json:"password"`
	ScrambledPassword string              `json:"scrambled_password"`
	PasswordChangedAt string              `json:"pwd_changed_at"`
	LandingPage       string              `json:"landing_page"`
	Comment           string              `json:"comment"`
	Email             string              `json:"email"`
	ApiKeys           string              `json:"apikeys"`
	Privilege         api.SelectedMapList `json:"priv"`
	Language          api.SelectedMap     `json:"language"`
	GroupMemberships  api.SelectedMapList `json:"group_memberships"`
	Fullname          string              `json:"descr"`
	Dashboard         string              `json:"dashboard"`
}

// CRUD operations

func (c *Controller) AddUser(ctx context.Context, resource *User) (string, error) {
	return api.Add(c.Client(), ctx, UserOpts, resource)
}

func (c *Controller) GetUser(ctx context.Context, id string) (*User, error) {
	return api.Get(c.Client(), ctx, UserOpts, &User{}, id)
}

func (c *Controller) UpdateUser(ctx context.Context, id string, resource *User) error {
	return api.Update(c.Client(), ctx, UserOpts, resource, id)
}

func (c *Controller) DeleteUser(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, UserOpts, id)
}
