// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package dnsmasq

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var DomainOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/dnsmasq/settings/add_domain", Method: "POST"},
	Read:        api.Endpoint{Path: "/dnsmasq/settings/get_domain", Method: "GET"},
	Update:      api.Endpoint{Path: "/dnsmasq/settings/set_domain", Method: "POST"},
	Delete:      api.Endpoint{Path: "/dnsmasq/settings/del_domain", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/dnsmasq/service/reconfigure", Method: "POST"},
	Monad:       "domainoverride",
}

// Data structs

type Domain struct {
	Sequence      string          `json:"sequence"`
	Domain        string          `json:"domain"`
	FirewallAlias api.SelectedMap `json:"ipset"`
	SourceIp      string          `json:"srcip"`
	Port          string          `json:"port"`
	Ip            string          `json:"ip"`
	Description   string          `json:"descr"`
}

// CRUD operations

func (c *Controller) AddDomain(ctx context.Context, resource *Domain) (string, error) {
	return api.Add(c.Client(), ctx, DomainOpts, resource)
}

func (c *Controller) GetDomain(ctx context.Context, id string) (*Domain, error) {
	return api.Get(c.Client(), ctx, DomainOpts, &Domain{}, id)
}

func (c *Controller) UpdateDomain(ctx context.Context, id string, resource *Domain) error {
	return api.Update(c.Client(), ctx, DomainOpts, resource, id)
}

func (c *Controller) DeleteDomain(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, DomainOpts, id)
}
