// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package dnsmasq

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var TagOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/dnsmasq/settings/add_tag", Method: "POST"},
	Read:        api.Endpoint{Path: "/dnsmasq/settings/get_tag", Method: "GET"},
	Update:      api.Endpoint{Path: "/dnsmasq/settings/set_tag", Method: "POST"},
	Delete:      api.Endpoint{Path: "/dnsmasq/settings/del_tag", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/dnsmasq/service/reconfigure", Method: "POST"},
	Monad:       "tag",
}

// Data structs

type Tag struct {
	Tag string `json:"tag"`
}

// CRUD operations

func (c *Controller) AddTag(ctx context.Context, resource *Tag) (string, error) {
	return api.Add(c.Client(), ctx, TagOpts, resource)
}

func (c *Controller) GetTag(ctx context.Context, id string) (*Tag, error) {
	return api.Get(c.Client(), ctx, TagOpts, &Tag{}, id)
}

func (c *Controller) UpdateTag(ctx context.Context, id string, resource *Tag) error {
	return api.Update(c.Client(), ctx, TagOpts, resource, id)
}

func (c *Controller) DeleteTag(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, TagOpts, id)
}
