// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package core

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type FirmwareActionResult struct {
	Status      string `json:"status"`
	MessageUUID string `json:"msg_uuid"`
}

type FirmwareInfoResponse struct {
	ProductID      string            `json:"product_id"`
	ProductVersion string            `json:"product_version"`
	Packages       []FirmwarePackage `json:"package"`
	Plugins        []FirmwarePackage `json:"plugin"`
}

type FirmwarePackage struct {
	Name       string `json:"name"`
	Version    string `json:"version"`
	Comment    string `json:"comment"`
	FlatSize   string `json:"flatsize"`
	Locked     string `json:"locked"`
	Automatic  string `json:"automatic"`
	License    string `json:"license"`
	Repository string `json:"repository"`
	Origin     string `json:"origin"`
	Provided   string `json:"provided"`
	Installed  string `json:"installed"`
	Path       string `json:"path"`
	Configured string `json:"configured"`
	Tier       string `json:"tier"`
}

type FirmwareRunningResponse struct {
	Status string `json:"status"`
}

type FirmwareUpgradeStatusResponse struct {
	Status string `json:"status"`
	Log    string `json:"log"`
}

// FirmwareInfo executes the Info RPC call of the Firmware controller
func (c *Controller) FirmwareInfo(ctx context.Context) (*FirmwareInfoResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/core/firmware/info", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &FirmwareInfoResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("info call failed: %w", err)
	}
	return result, nil
}

// FirmwareInstall executes the Install RPC call of the Firmware controller
func (c *Controller) FirmwareInstall(ctx context.Context, packageName string) (*FirmwareActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, packageName)

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/core/firmware/install", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &FirmwareActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("install call failed: %w", err)
	}
	return result, nil
}

// FirmwareRemove executes the Remove RPC call of the Firmware controller
func (c *Controller) FirmwareRemove(ctx context.Context, packageName string) (*FirmwareActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, packageName)

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/core/firmware/remove", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &FirmwareActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("remove call failed: %w", err)
	}
	return result, nil
}

// FirmwareLock executes the Lock RPC call of the Firmware controller
func (c *Controller) FirmwareLock(ctx context.Context, packageName string) (*FirmwareActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, packageName)

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/core/firmware/lock", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &FirmwareActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("lock call failed: %w", err)
	}
	return result, nil
}

// FirmwareUnlock executes the Unlock RPC call of the Firmware controller
func (c *Controller) FirmwareUnlock(ctx context.Context, packageName string) (*FirmwareActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, packageName)

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/core/firmware/unlock", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &FirmwareActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("unlock call failed: %w", err)
	}
	return result, nil
}

// FirmwareRunning executes the Running RPC call of the Firmware controller
func (c *Controller) FirmwareRunning(ctx context.Context) (*FirmwareRunningResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/core/firmware/running", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &FirmwareRunningResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("running call failed: %w", err)
	}
	return result, nil
}

// FirmwareUpgradeStatus executes the UpgradeStatus RPC call of the Firmware controller
func (c *Controller) FirmwareUpgradeStatus(ctx context.Context) (*FirmwareUpgradeStatusResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/core/firmware/upgradestatus", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &FirmwareUpgradeStatusResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("upgradeStatus call failed: %w", err)
	}
	return result, nil
}
