// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package core

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type HasyncResponse struct {
	Hasync HasyncSettings `json:"hasync"`
}

type HasyncSettings struct {
	DisablePreempt  string              `json:"disablepreempt"`
	DisconnectPPPs  string              `json:"disconnectppps"`
	PfsyncInterface api.SelectedMap     `json:"pfsyncinterface"`
	PfsyncPeerIP    string              `json:"pfsyncpeerip"`
	PfsyncVersion   api.SelectedMap     `json:"pfsyncversion"`
	PfsyncDefer     string              `json:"pfsyncdefer"`
	SynchronizeToIP string              `json:"synchronizetoip"`
	VerifyPeer      string              `json:"verifypeer"`
	Username        string              `json:"username"`
	Password        string              `json:"password"`
	SyncItems       api.SelectedMapList `json:"syncitems"`
}

// HasyncGet executes the Get RPC call of the Hasync controller
func (c *Controller) HasyncGet(ctx context.Context) (*HasyncResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/core/hasync/get", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &HasyncResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("get call failed: %w", err)
	}
	return result, nil
}

// HasyncSet executes the Set RPC call of the Hasync controller
func (c *Controller) HasyncSet(ctx context.Context, hasync *HasyncSettings) (*api.ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["hasync"] = hasync

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/core/hasync/set", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &api.ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("set call failed: %w", err)
	}
	return result, nil
}

// HasyncReconfigure executes the Reconfigure RPC call of the Hasync controller
func (c *Controller) HasyncReconfigure(ctx context.Context) (*api.ReconfigureStatusResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/core/hasync/reconfigure", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &api.ReconfigureStatusResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("reconfigure call failed: %w", err)
	}
	return result, nil
}
