// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package core

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type Status struct {
	StatusCode  int    `json:"statusCode"`
	Message     string `json:"message"`
	LogLocation string `json:"logLocation"`
	Timestamp   string `json:"timestamp"`
	Status      string `json:"status"`
}

type SystemStatus struct {
	CrashReporter Status `json:"CrashReporter"`
	Firewall      Status `json:"Firewall"`
	System        Status `json:"System"`
}

// SystemHalt executes the Halt RPC call of the System controller
func (c *Controller) SystemHalt(ctx context.Context) (*api.ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/core/system/halt", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &api.ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("halt call failed: %w", err)
	}
	return result, nil
}

// SystemReboot executes the Reboot RPC call of the System controller
func (c *Controller) SystemReboot(ctx context.Context) (*api.ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/core/system/reboot", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &api.ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("reboot call failed: %w", err)
	}
	return result, nil
}

// SystemStatus executes the Status RPC call of the System controller
func (c *Controller) SystemStatus(ctx context.Context) (*SystemStatus, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/core/system/status", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &SystemStatus{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("status call failed: %w", err)
	}
	return result, nil
}

// SystemDismissStatus executes the DismissStatus RPC call of the System controller
func (c *Controller) SystemDismissStatus(ctx context.Context, subject string) (*api.ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["subject"] = subject

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/core/system/dismiss_status", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &api.ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("dismissStatus call failed: %w", err)
	}
	return result, nil
}
