// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package core

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var TunableOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/core/tunables/add_item", Method: "POST"},
	Read:        api.Endpoint{Path: "/core/tunables/get_item", Method: "GET"},
	Update:      api.Endpoint{Path: "/core/tunables/set_item", Method: "POST"},
	Delete:      api.Endpoint{Path: "/core/tunables/del_item", Method: "POST"},
	Search:      api.Endpoint{Path: "/core/tunables/search_item", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/core/tunables/reconfigure", Method: "POST"},
	Monad:       "sysctl",
}

// Data structs

type Tunable struct {
	Tunable     string `json:"tunable"`
	Value       string `json:"value"`
	Description string `json:"descr"`
}

// CRUD operations

func (c *Controller) AddTunable(ctx context.Context, resource *Tunable) (string, error) {
	return api.Add(c.Client(), ctx, TunableOpts, resource)
}

func (c *Controller) GetTunable(ctx context.Context, id string) (*Tunable, error) {
	return api.Get(c.Client(), ctx, TunableOpts, &Tunable{}, id)
}

func (c *Controller) SearchTunable(ctx context.Context) (*api.SearchResponse[Tunable], error) {
	return api.Search[Tunable](c.Client(), ctx, TunableOpts.Search)
}

func (c *Controller) UpdateTunable(ctx context.Context, id string, resource *Tunable) error {
	return api.Update(c.Client(), ctx, TunableOpts, resource, id)
}

func (c *Controller) DeleteTunable(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, TunableOpts, id)
}
