// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package caddy

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var AccessListOpts = api.ReqOpts{
	AddEndpoint:         "/caddy/reverse_proxy/add_access_list",
	GetEndpoint:         "/caddy/reverse_proxy/get_access_list",
	UpdateEndpoint:      "/caddy/reverse_proxy/set_access_list",
	DeleteEndpoint:      "/caddy/reverse_proxy/del_access_list",
	SearchEndpoint:      "/caddy/reverse_proxy/search_access_list",
	ReconfigureEndpoint: caddyReconfigureEndpoint,
	Monad:               "accesslist",
}

// Data structs

type AccessList struct {
	Name                string              `json:"accesslistName"`
	ClientIPs           api.SelectedMapList `json:"clientIps"`
	Invert              string              `json:"accesslistInvert"`
	HTTPResponseCode    string              `json:"HttpResponseCode"`
	HTTPResponseMessage string              `json:"HttpResponseMessage"`
	RequestMatcher      api.SelectedMap     `json:"RequestMatcher"`
	Description         string              `json:"description"`
}

// CRUD operations

func (c *Controller) AddAccessList(ctx context.Context, resource *AccessList) (string, error) {
	return api.Add(c.Client(), ctx, AccessListOpts, resource)
}

func (c *Controller) GetAccessList(ctx context.Context, id string) (*AccessList, error) {
	return api.Get(c.Client(), ctx, AccessListOpts, &AccessList{}, id)
}

func (c *Controller) SearchAccessList(ctx context.Context) (*api.SearchResponse[AccessList], error) {
	return api.Search[AccessList](c.Client(), ctx, AccessListOpts.SearchEndpoint)
}

func (c *Controller) UpdateAccessList(ctx context.Context, id string, resource *AccessList) error {
	return api.Update(c.Client(), ctx, AccessListOpts, resource, id)
}

func (c *Controller) DeleteAccessList(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, AccessListOpts, id)
}
