// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package caddy

import "github.com/biptec/opnsense-go/pkg/api"

// Controller for caddy
type Controller struct {
	Api *api.Client
}

func (c *Controller) Client() *api.Client {
	return c.Api
}
