// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package caddy

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var DomainOpts = api.ReqOpts{
	AddEndpoint:         "/caddy/reverse_proxy/add_reverse_proxy",
	GetEndpoint:         "/caddy/reverse_proxy/get_reverse_proxy",
	UpdateEndpoint:      "/caddy/reverse_proxy/set_reverse_proxy",
	DeleteEndpoint:      "/caddy/reverse_proxy/del_reverse_proxy",
	SearchEndpoint:      "/caddy/reverse_proxy/search_reverse_proxy",
	ReconfigureEndpoint: caddyReconfigureEndpoint,
	Monad:               "reverse",
}

// Data structs

type Domain struct {
	Enabled                    string              `json:"enabled"`
	Domain                     string              `json:"FromDomain"`
	Port                       string              `json:"FromPort"`
	AccessList                 api.SelectedMap     `json:"accesslist"`
	BasicAuth                  api.SelectedMapList `json:"basicauth"`
	Description                string              `json:"description"`
	DNSChallenge               string              `json:"DnsChallenge"`
	DNSChallengeOverrideDomain string              `json:"DnsChallengeOverrideDomain"`
	CustomCertificate          api.SelectedMap     `json:"CustomCertificate"`
	AccessLog                  string              `json:"AccessLog"`
	DynamicDNS                 string              `json:"DynDns"`
	ACMEPassthrough            string              `json:"AcmePassthrough"`
	DisableTLS                 api.SelectedMap     `json:"DisableTls"`
	ClientAuthMode             api.SelectedMap     `json:"ClientAuthMode"`
	ClientAuthTrustPool        api.SelectedMapList `json:"ClientAuthTrustPool"`
}

// CRUD operations

func (c *Controller) AddDomain(ctx context.Context, resource *Domain) (string, error) {
	return api.Add(c.Client(), ctx, DomainOpts, resource)
}

func (c *Controller) GetDomain(ctx context.Context, id string) (*Domain, error) {
	return api.Get(c.Client(), ctx, DomainOpts, &Domain{}, id)
}

func (c *Controller) SearchDomain(ctx context.Context) (*api.SearchResponse[Domain], error) {
	return api.Search[Domain](c.Client(), ctx, DomainOpts.SearchEndpoint)
}

func (c *Controller) UpdateDomain(ctx context.Context, id string, resource *Domain) error {
	return api.Update(c.Client(), ctx, DomainOpts, resource, id)
}

func (c *Controller) DeleteDomain(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, DomainOpts, id)
}
