// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package caddy

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var HandlerOpts = api.ReqOpts{
	AddEndpoint:         "/caddy/reverse_proxy/add_handle",
	GetEndpoint:         "/caddy/reverse_proxy/get_handle",
	UpdateEndpoint:      "/caddy/reverse_proxy/set_handle",
	DeleteEndpoint:      "/caddy/reverse_proxy/del_handle",
	SearchEndpoint:      "/caddy/reverse_proxy/search_handle",
	ReconfigureEndpoint: caddyReconfigureEndpoint,
	Monad:               "handle",
}

// Data structs

type Handler struct {
	Enabled                            string              `json:"enabled"`
	Domain                             api.SelectedMap     `json:"reverse"`
	Subdomain                          api.SelectedMap     `json:"subdomain"`
	Type                               api.SelectedMap     `json:"HandleType"`
	Path                               string              `json:"HandlePath"`
	AccessList                         api.SelectedMap     `json:"accesslist"`
	BasicAuth                          api.SelectedMapList `json:"basicauth"`
	Headers                            api.SelectedMapList `json:"header"`
	Directive                          api.SelectedMap     `json:"HandleDirective"`
	UpstreamDomains                    api.SelectedMapList `json:"ToDomain"`
	UpstreamPort                       string              `json:"ToPort"`
	UpstreamPath                       string              `json:"ToPath"`
	ForwardAuth                        string              `json:"ForwardAuth"`
	UpstreamProtocol                   api.SelectedMap     `json:"HttpTls"`
	HTTPVersion                        api.SelectedMap     `json:"HttpVersion"`
	HTTPKeepalive                      string              `json:"HttpKeepalive"`
	TLSSkipVerify                      string              `json:"HttpTlsInsecureSkipVerify"`
	TLSTrustPool                       api.SelectedMap     `json:"HttpTlsTrustedCaCerts"`
	TLSServerName                      string              `json:"HttpTlsServerName"`
	LoadBalancingPolicy                api.SelectedMap     `json:"lb_policy"`
	LoadBalancingRetries               string              `json:"lb_retries"`
	LoadBalancingTryDuration           string              `json:"lb_try_duration"`
	LoadBalancingTryInterval           string              `json:"lb_try_interval"`
	PassiveHealthFailDuration          string              `json:"PassiveHealthFailDuration"`
	PassiveHealthMaxFails              string              `json:"PassiveHealthMaxFails"`
	PassiveHealthUnhealthyStatus       string              `json:"PassiveHealthUnhealthyStatus"`
	PassiveHealthUnhealthyLatency      string              `json:"PassiveHealthUnhealthyLatency"`
	PassiveHealthUnhealthyRequestCount string              `json:"PassiveHealthUnhealthyRequestCount"`
	HealthURI                          string              `json:"health_uri"`
	HealthUpstream                     string              `json:"health_upstream"`
	HealthPort                         string              `json:"health_port"`
	HealthInterval                     string              `json:"health_interval"`
	HealthPasses                       string              `json:"health_passes"`
	HealthFails                        string              `json:"health_fails"`
	HealthTimeout                      string              `json:"health_timeout"`
	HealthStatus                       string              `json:"health_status"`
	HealthBody                         string              `json:"health_body"`
	HealthFollowRedirects              string              `json:"health_follow_redirects"`
	Description                        string              `json:"description"`
}

// CRUD operations

func (c *Controller) AddHandler(ctx context.Context, resource *Handler) (string, error) {
	return api.Add(c.Client(), ctx, HandlerOpts, resource)
}

func (c *Controller) GetHandler(ctx context.Context, id string) (*Handler, error) {
	return api.Get(c.Client(), ctx, HandlerOpts, &Handler{}, id)
}

func (c *Controller) SearchHandler(ctx context.Context) (*api.SearchResponse[Handler], error) {
	return api.Search[Handler](c.Client(), ctx, HandlerOpts.SearchEndpoint)
}

func (c *Controller) UpdateHandler(ctx context.Context, id string, resource *Handler) error {
	return api.Update(c.Client(), ctx, HandlerOpts, resource, id)
}

func (c *Controller) DeleteHandler(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, HandlerOpts, id)
}
