// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package caddy

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var HeaderOpts = api.ReqOpts{
	AddEndpoint:         "/caddy/reverse_proxy/add_header",
	GetEndpoint:         "/caddy/reverse_proxy/get_header",
	GetMethod:           "POST",
	UpdateEndpoint:      "/caddy/reverse_proxy/set_header",
	DeleteEndpoint:      "/caddy/reverse_proxy/del_header",
	SearchEndpoint:      "/caddy/reverse_proxy/search_header",
	ReconfigureEndpoint: caddyReconfigureEndpoint,
	Monad:               "header",
}

// Data structs

type Header struct {
	UUID        string          `json:"uuid,omitempty"`
	Direction   api.SelectedMap `json:"HeaderUpDown"`
	Name        string          `json:"HeaderType"`
	Value       string          `json:"HeaderValue"`
	Replace     string          `json:"HeaderReplace"`
	Description string          `json:"description"`
}

// CRUD operations

func (c *Controller) AddHeader(ctx context.Context, resource *Header) (string, error) {
	return api.Add(c.Client(), ctx, HeaderOpts, resource)
}

func (c *Controller) GetHeader(ctx context.Context, id string) (*Header, error) {
	return api.Get(c.Client(), ctx, HeaderOpts, &Header{}, id)
}

func (c *Controller) SearchHeader(ctx context.Context) (*api.SearchResponse[Header], error) {
	return api.Search[Header](c.Client(), ctx, HeaderOpts.SearchEndpoint)
}

func (c *Controller) UpdateHeader(ctx context.Context, id string, resource *Header) error {
	return api.Update(c.Client(), ctx, HeaderOpts, resource, id)
}

func (c *Controller) DeleteHeader(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, HeaderOpts, id)
}
