// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package caddy

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type GeneralSettings struct {
	Enabled                       string              `json:"enabled"`
	EnableLayer4                  string              `json:"EnableLayer4"`
	HTTPPort                      string              `json:"HttpPort"`
	HTTPSPort                     string              `json:"HttpsPort"`
	ListenAddresses               api.SelectedMapList `json:"ListenAddresses"`
	ACMEEmail                     string              `json:"TlsEmail"`
	AutoHTTPS                     api.SelectedMap     `json:"TlsAutoHttps"`
	DNSProvider                   api.SelectedMap     `json:"TlsDnsProvider"`
	DNSAPIKey                     string              `json:"TlsDnsApiKey"`
	DNSPropagationTimeoutDisabled string              `json:"TlsDnsPropagationTimeout"`
	DNSPropagationTimeout         string              `json:"TlsDnsPropagationTimeoutPeriod"`
	DNSPropagationDelay           string              `json:"TlsDnsPropagationDelay"`
	DNSPropagationResolvers       string              `json:"TlsDnsPropagationResolvers"`
	DNSECHDomain                  string              `json:"TlsDnsEchDomain"`
	AccessList                    api.SelectedMap     `json:"accesslist"`
	ClientIPHeaders               api.SelectedMapList `json:"ClientIpHeaders"`
	RunAsUser                     api.SelectedMap     `json:"DisableSuperuser"`
	GracePeriod                   string              `json:"GracePeriod"`
	HTTPVersions                  api.SelectedMapList `json:"HttpVersions"`
	ReadBodyTimeout               string              `json:"timeout_read_body"`
	ReadHeaderTimeout             string              `json:"timeout_read_header"`
	WriteTimeout                  string              `json:"timeout_write"`
	IdleTimeout                   string              `json:"timeout_idle"`
	LogCredentials                string              `json:"LogCredentials"`
	PlainAccessLog                string              `json:"LogAccessPlain"`
	PlainAccessLogKeep            string              `json:"LogAccessPlainKeep"`
	LogLevel                      api.SelectedMap     `json:"LogLevel"`
	DynamicDNSSimpleHTTP          string              `json:"DynDnsSimpleHttp"`
	DynamicDNSInterface           api.SelectedMap     `json:"DynDnsInterface"`
	DynamicDNSInterval            string              `json:"DynDnsInterval"`
	DynamicDNSIPVersions          api.SelectedMap     `json:"DynDnsIpVersions"`
	DynamicDNSTTL                 string              `json:"DynDnsTtl"`
	DynamicDNSUpdateOnly          string              `json:"DynDnsUpdateOnly"`
	AuthProvider                  api.SelectedMap     `json:"AuthProvider"`
	AuthUpstreamDomain            string              `json:"AuthToDomain"`
	AuthUpstreamPort              string              `json:"AuthToPort"`
	AuthUpstreamProtocol          api.SelectedMap     `json:"AuthToTls"`
	AuthUpstreamURI               string              `json:"AuthToUri"`
	AuthCopyHeaders               api.SelectedMapList `json:"CopyHeaders"`
}

type Settings struct {
	General GeneralSettings `json:"general"`
}

type SettingsResponse struct {
	Caddy Settings `json:"caddy"`
}

// SettingsGet executes the Get RPC call of the Settings controller
func (c *Controller) SettingsGet(ctx context.Context) (*SettingsResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/caddy/general/get", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &SettingsResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("get call failed: %w", err)
	}
	return result, nil
}

// SettingsSet executes the Set RPC call of the Settings controller
func (c *Controller) SettingsSet(ctx context.Context, caddy *Settings) (*api.ActionResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["caddy"] = caddy

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/caddy/general/set", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &api.ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("set call failed: %w", err)
	}
	return result, nil
}
