// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package acmeclient

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type AccountActionResponse struct {
	Result   string `json:"result,omitempty"`
	Response string `json:"response,omitempty"`
}

// AccountRegister executes the Register RPC call of the Account controller
func (c *Controller) AccountRegister(ctx context.Context, uuid string) (*AccountActionResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, uuid)

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/acmeclient/accounts/register", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &AccountActionResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("register call failed: %w", err)
	}
	return result, nil
}
