// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package acmeclient

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var AccountOpts = api.ReqOpts{
	Create: api.Endpoint{Path: "/acmeclient/accounts/add", Method: "POST"},
	Read:   api.Endpoint{Path: "/acmeclient/accounts/get", Method: "GET"},
	Update: api.Endpoint{Path: "/acmeclient/accounts/update", Method: "POST"},
	Delete: api.Endpoint{Path: "/acmeclient/accounts/del", Method: "POST"},
	Search: api.Endpoint{Path: "/acmeclient/accounts/search", Method: "POST"},
	Monad:  "account",
}

// Data structs

type Account struct {
	Enabled          string          `json:"enabled"`
	Name             string          `json:"name"`
	Description      string          `json:"description"`
	Email            string          `json:"email"`
	CA               api.SelectedMap `json:"ca"`
	CustomCA         string          `json:"custom_ca"`
	StatusCode       string          `json:"statusCode"`
	StatusLastUpdate string          `json:"statusLastUpdate"`
}

// CRUD operations

func (c *Controller) AddAccount(ctx context.Context, resource *Account) (string, error) {
	return api.Add(c.Client(), ctx, AccountOpts, resource)
}

func (c *Controller) GetAccount(ctx context.Context, id string) (*Account, error) {
	return api.Get(c.Client(), ctx, AccountOpts, &Account{}, id)
}

func (c *Controller) SearchAccount(ctx context.Context) (*api.SearchResponse[Account], error) {
	return api.Search[Account](c.Client(), ctx, AccountOpts.Search)
}

func (c *Controller) UpdateAccount(ctx context.Context, id string, resource *Account) error {
	return api.Update(c.Client(), ctx, AccountOpts, resource, id)
}

func (c *Controller) DeleteAccount(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, AccountOpts, id)
}
