// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package acmeclient

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var ActionOpts = api.ReqOpts{
	Create: api.Endpoint{Path: "/acmeclient/actions/add", Method: "POST"},
	Read:   api.Endpoint{Path: "/acmeclient/actions/get", Method: "GET"},
	Update: api.Endpoint{Path: "/acmeclient/actions/update", Method: "POST"},
	Delete: api.Endpoint{Path: "/acmeclient/actions/del", Method: "POST"},
	Search: api.Endpoint{Path: "/acmeclient/actions/search", Method: "POST"},
	Monad:  "action",
}

// Data structs

type Action struct {
	Enabled     string          `json:"enabled"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Type        api.SelectedMap `json:"type"`
}

// CRUD operations

func (c *Controller) AddAction(ctx context.Context, resource *Action) (string, error) {
	return api.Add(c.Client(), ctx, ActionOpts, resource)
}

func (c *Controller) GetAction(ctx context.Context, id string) (*Action, error) {
	return api.Get(c.Client(), ctx, ActionOpts, &Action{}, id)
}

func (c *Controller) SearchAction(ctx context.Context) (*api.SearchResponse[Action], error) {
	return api.Search[Action](c.Client(), ctx, ActionOpts.Search)
}

func (c *Controller) UpdateAction(ctx context.Context, id string, resource *Action) error {
	return api.Update(c.Client(), ctx, ActionOpts, resource, id)
}

func (c *Controller) DeleteAction(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, ActionOpts, id)
}
