// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package acmeclient

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type CertificateActionResponse struct {
	Result   string `json:"result,omitempty"`
	Response string `json:"response,omitempty"`
}

// CertificateSign executes the Sign RPC call of the Certificate controller
func (c *Controller) CertificateSign(ctx context.Context, uuid string) (*CertificateActionResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, uuid)

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/acmeclient/certificates/sign", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &CertificateActionResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("sign call failed: %w", err)
	}
	return result, nil
}

// CertificateAutomation executes the Automation RPC call of the Certificate controller
func (c *Controller) CertificateAutomation(ctx context.Context, uuid string) (*CertificateActionResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, uuid)

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/acmeclient/certificates/automation", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &CertificateActionResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("automation call failed: %w", err)
	}
	return result, nil
}
