// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package acmeclient

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var CertificateOpts = api.ReqOpts{
	Create: api.Endpoint{Path: "/acmeclient/certificates/add", Method: "POST"},
	Read:   api.Endpoint{Path: "/acmeclient/certificates/get", Method: "GET"},
	Update: api.Endpoint{Path: "/acmeclient/certificates/update", Method: "POST"},
	Delete: api.Endpoint{Path: "/acmeclient/certificates/del", Method: "POST"},
	Search: api.Endpoint{Path: "/acmeclient/certificates/search", Method: "POST"},
	Monad:  "certificate",
}

// Data structs

type Certificate struct {
	Enabled          string              `json:"enabled"`
	Name             string              `json:"name"`
	Description      string              `json:"description"`
	AltNames         api.SelectedMapList `json:"altNames"`
	Account          api.SelectedMap     `json:"account"`
	ValidationMethod api.SelectedMap     `json:"validationMethod"`
	KeyLength        api.SelectedMap     `json:"keyLength"`
	OCSP             string              `json:"ocsp"`
	Profile          string              `json:"profile"`
	RestartActions   api.SelectedMapList `json:"restartActions"`
	AutoRenewal      string              `json:"autoRenewal"`
	RenewInterval    string              `json:"renewInterval"`
	AliasMode        api.SelectedMap     `json:"aliasmode"`
	DomainAlias      string              `json:"domainalias"`
	ChallengeAlias   string              `json:"challengealias"`
	CertRefID        string              `json:"certRefId"`
	LastUpdate       string              `json:"lastUpdate"`
	StatusCode       string              `json:"statusCode"`
	StatusLastUpdate string              `json:"statusLastUpdate"`
}

// CRUD operations

func (c *Controller) AddCertificate(ctx context.Context, resource *Certificate) (string, error) {
	return api.Add(c.Client(), ctx, CertificateOpts, resource)
}

func (c *Controller) GetCertificate(ctx context.Context, id string) (*Certificate, error) {
	return api.Get(c.Client(), ctx, CertificateOpts, &Certificate{}, id)
}

func (c *Controller) SearchCertificate(ctx context.Context) (*api.SearchResponse[Certificate], error) {
	return api.Search[Certificate](c.Client(), ctx, CertificateOpts.Search)
}

func (c *Controller) UpdateCertificate(ctx context.Context, id string, resource *Certificate) error {
	return api.Update(c.Client(), ctx, CertificateOpts, resource, id)
}

func (c *Controller) DeleteCertificate(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, CertificateOpts, id)
}
