// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package acmeclient

import (
	"context"
	"fmt"

	"github.com/biptec/opnsense-go/pkg/api"
)

// Data structs

type SaveResult struct {
	Result      string                 `json:"result"`
	Validations map[string]interface{} `json:"validations,omitempty"`
}

type Settings struct {
	Enabled            string          `json:"enabled"`
	AutoRenewal        string          `json:"autoRenewal"`
	UpdateCron         api.SelectedMap `json:"UpdateCron"`
	Environment        api.SelectedMap `json:"environment"`
	ChallengePort      string          `json:"challengePort"`
	TLSChallengePort   string          `json:"TLSchallengePort"`
	RestartTimeout     string          `json:"restartTimeout"`
	HAProxyIntegration string          `json:"haproxyIntegration"`
	HAProxyACLRef      api.SelectedMap `json:"haproxyAclRef"`
	HAProxyActionRef   api.SelectedMap `json:"haproxyActionRef"`
	HAProxyServerRef   api.SelectedMap `json:"haproxyServerRef"`
	HAProxyBackendRef  api.SelectedMap `json:"haproxyBackendRef"`
	LogLevel           api.SelectedMap `json:"logLevel"`
	ShowIntro          string          `json:"showIntro"`
}

type SettingsResponse struct {
	AcmeClient SettingsRoot `json:"acmeclient"`
}

type SettingsRoot struct {
	Settings Settings `json:"settings"`
}

// SettingsGet executes the Get RPC call of the Settings controller
func (c *Controller) SettingsGet(ctx context.Context) (*SettingsResponse, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/acmeclient/settings/get", Method: "GET"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &SettingsResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("get call failed: %w", err)
	}
	return result, nil
}

// SettingsSet executes the Set RPC call of the Settings controller
func (c *Controller) SettingsSet(ctx context.Context, root *SettingsRoot) (*SaveResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	bodyParams["acmeclient"] = root

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/acmeclient/settings/set", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &SaveResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("set call failed: %w", err)
	}
	return result, nil
}

// SettingsFetchCronIntegration executes the FetchCronIntegration RPC call of the Settings controller
func (c *Controller) SettingsFetchCronIntegration(ctx context.Context) (*SaveResult, error) {

	callParams := []string{}
	queryParams := make(map[string]string)
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		Endpoint:        api.Endpoint{Path: "/acmeclient/settings/fetch_cron_integration", Method: "POST"},
		PathParameters:  callParams,
		QueryParameters: queryParams,
		BodyParameters:  bodyParams,
	}

	resultData := &SaveResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("fetchCronIntegration call failed: %w", err)
	}
	return result, nil
}
