// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package acmeclient

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var ValidationOpts = api.ReqOpts{
	Create: api.Endpoint{Path: "/acmeclient/validations/add", Method: "POST"},
	Read:   api.Endpoint{Path: "/acmeclient/validations/get", Method: "GET"},
	Update: api.Endpoint{Path: "/acmeclient/validations/update", Method: "POST"},
	Delete: api.Endpoint{Path: "/acmeclient/validations/del", Method: "POST"},
	Search: api.Endpoint{Path: "/acmeclient/validations/search", Method: "POST"},
	Monad:  "validation",
}

// Data structs

type Validation struct {
	Enabled           string          `json:"enabled"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Method            api.SelectedMap `json:"method"`
	DNSService        api.SelectedMap `json:"dns_service"`
	DNSNsupdateServer string          `json:"dns_nsupdate_server"`
	DNSNsupdateZone   string          `json:"dns_nsupdate_zone"`
	DNSNsupdateKey    string          `json:"dns_nsupdate_key"`
}

// CRUD operations

func (c *Controller) AddValidation(ctx context.Context, resource *Validation) (string, error) {
	return api.Add(c.Client(), ctx, ValidationOpts, resource)
}

func (c *Controller) GetValidation(ctx context.Context, id string) (*Validation, error) {
	return api.Get(c.Client(), ctx, ValidationOpts, &Validation{}, id)
}

func (c *Controller) SearchValidation(ctx context.Context) (*api.SearchResponse[Validation], error) {
	return api.Search[Validation](c.Client(), ctx, ValidationOpts.Search)
}

func (c *Controller) UpdateValidation(ctx context.Context, id string, resource *Validation) error {
	return api.Update(c.Client(), ctx, ValidationOpts, resource, id)
}

func (c *Controller) DeleteValidation(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, ValidationOpts, id)
}
