// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package unbound

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var AclOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/unbound/settings/add_acl", Method: "POST"},
	Read:        api.Endpoint{Path: "/unbound/settings/get_acl", Method: "GET"},
	Update:      api.Endpoint{Path: "/unbound/settings/set_acl", Method: "POST"},
	Delete:      api.Endpoint{Path: "/unbound/settings/del_acl", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/unbound/service/reconfigure", Method: "POST"},
	Monad:       "acl",
}

// Data structs

type Acl struct {
	Enabled     string              `json:"enabled"`
	Name        string              `json:"name"`
	Action      api.SelectedMap     `json:"action"`
	Networks    api.SelectedMapList `json:"networks"`
	Description string              `json:"description"`
}

// CRUD operations

func (c *Controller) AddAcl(ctx context.Context, resource *Acl) (string, error) {
	return api.Add(c.Client(), ctx, AclOpts, resource)
}

func (c *Controller) GetAcl(ctx context.Context, id string) (*Acl, error) {
	return api.Get(c.Client(), ctx, AclOpts, &Acl{}, id)
}

func (c *Controller) UpdateAcl(ctx context.Context, id string, resource *Acl) error {
	return api.Update(c.Client(), ctx, AclOpts, resource, id)
}

func (c *Controller) DeleteAcl(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, AclOpts, id)
}
