// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package unbound

import (
	"context"

	"github.com/biptec/opnsense-go/pkg/api"
)

var HostAliasOpts = api.ReqOpts{
	Create:      api.Endpoint{Path: "/unbound/settings/addHostAlias", Method: "POST"},
	Read:        api.Endpoint{Path: "/unbound/settings/getHostAlias", Method: "GET"},
	Update:      api.Endpoint{Path: "/unbound/settings/setHostAlias", Method: "POST"},
	Delete:      api.Endpoint{Path: "/unbound/settings/delHostAlias", Method: "POST"},
	Reconfigure: api.Endpoint{Path: "/unbound/service/reconfigure", Method: "POST"},
	Monad:       "alias",
}

// Data structs

type HostAlias struct {
	Enabled     string          `json:"enabled"`
	Host        api.SelectedMap `json:"host"`
	Hostname    string          `json:"hostname"`
	Domain      string          `json:"domain"`
	Description string          `json:"description"`
}

// CRUD operations

func (c *Controller) AddHostAlias(ctx context.Context, resource *HostAlias) (string, error) {
	return api.Add(c.Client(), ctx, HostAliasOpts, resource)
}

func (c *Controller) GetHostAlias(ctx context.Context, id string) (*HostAlias, error) {
	return api.Get(c.Client(), ctx, HostAliasOpts, &HostAlias{}, id)
}

func (c *Controller) UpdateHostAlias(ctx context.Context, id string, resource *HostAlias) error {
	return api.Update(c.Client(), ctx, HostAliasOpts, resource, id)
}

func (c *Controller) DeleteHostAlias(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, HostAliasOpts, id)
}
